import ReportDocument from "./ReportDocument.jsx";

export default function RoomResults({room,onRetry,onReturn,onCompareRetry,example=false}) {
  const comparison=room.competition, report=room.your_report;
  const ready=comparison?.status === "ready" && comparison?.criteria?.length;
  const name=id=>room.participants?.[String(id)]?.display_name || "Участник";
  return <div className="room-results">
    {room.mode === "duel" && <section className="room-comparison"><span className="eyebrow">ОБЩИЙ РЕЗУЛЬТАТ · ДВА ИНТЕРВЬЮ</span><h2>{!ready ? "Сравнение пока недоступно" : comparison.tie ? "Равный результат по критериям задания" : `В этой попытке сильнее — ${name(comparison.winner_id)}`}</h2><p>{comparison?.summary || "Сравнение появится после завершения обеих попыток."}</p>{ready&&<><p className="room-score-note">Каждый критерий: 0–4. Победитель определяется суммой этих же оценок. Это разбор учебной попытки.</p><div className="room-comparison-table"><table><thead><tr><th>Критерий</th>{Object.keys(comparison.scores).map(id=><th key={id}>{name(id)}<strong>{comparison.scores[id]} / {comparison.maximum}</strong></th>)}</tr></thead><tbody>{comparison.criteria.map(row=><tr key={row.id}><th>{row.label}</th>{Object.entries(row.candidates).map(([id,item])=><td key={id}><b>{item.score} / 4</b><blockquote>«{item.quote}»</blockquote></td>)}</tr>)}</tbody></table></div></>}{!ready&&comparison?.status==="unavailable"&&onCompareRetry&&<button className="subtle-button" onClick={onCompareRetry}>Повторить сравнение</button>}</section>}
    {room.mode === "human" && <section className="room-comparison"><span className="eyebrow">ОБЩИЙ РЕЗУЛЬТАТ ВСТРЕЧИ</span><h2>Что удалось согласовать</h2><p>Это совместная практика. Итог — договорённость и открытые условия, без выбора победителя.</p>{room.shared_result?.terms?.length ? <div className="room-shared-terms">{room.shared_result.terms.map((term,i)=><article key={i}><b>{term.label}</b><p>{term.proposed}</p><p>{term.confirmed}</p></article>)}</div> : <p>Явно подтверждённые условия в разборе не найдены. Посмотрите сохранённые реплики в личном отчёте.</p>}</section>}
    {report ? <ReportDocument report={report} example={example} onRetry={onRetry} retryLabel="Повторить условия встречи" onReturn={onReturn}/> : <section className="practice-status-panel"><h2>Личный разбор пока недоступен</h2><p>Он появится, когда будут обработаны ваши ответы.</p></section>}
    {report?.competition_feedback && <details className="room-personal-feedback"><summary>Личная рекомендация по интервью</summary><h3>Что получилось</h3><p>{report.competition_feedback.strength}</p><blockquote>«{report.competition_feedback.evidence}»</blockquote><h3>Что попробовать иначе</h3><p>{report.competition_feedback.improvement}</p><p>{report.competition_feedback.better_answer}</p></details>}
  </div>;
}
