import { useEffect, useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { api, transcribeWav } from "./api";

type Scores={trust:number;goal:number;control:number;eq:number};
type Setup={userName:string;userRole:string;opponentRole:string;problem:string;goal:string;character:string;level:string;difficulty:number;industry:string;companySize:string;culture:string;company:string;position:string};
type Analysis={turn:number;metrics:Scores;comment:string};
type Report={verdict:string;metrics:Scores;note:string;recommendations:string[]};
type Session={id:string;mode:"negotiation"|"interview";roomId?:string;roomQuestions?:string[];status?:string;provider?:string;messages:{role:"user"|"assistant";content:string}[];analysis?:Analysis[];report?:Report};
type Status={available:boolean;provider:string|null;voiceAvailable:boolean};
type Preset={id:string;name:string;setup:Setup&{mode:"negotiation"|"interview";scenarioId?:string}};
const initial:Setup={userName:"",userRole:"",opponentRole:"",problem:"",goal:"",character:"neutral",level:"intermediate",difficulty:2,industry:"",companySize:"",culture:"",company:"",position:""};
const names:Record<keyof Scores,string>={trust:"Доверие",goal:"Цель",control:"Контроль",eq:"EQ"};
async function toWav(blob:Blob) {
  const context=new AudioContext();
  try {
    const decoded=await context.decodeAudioData(await blob.arrayBuffer());
    const offline=new OfflineAudioContext(1,Math.ceil(decoded.duration*16000),16000);
    const source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start();
    const rendered=await offline.startRendering();const samples=rendered.getChannelData(0);
    const buffer=new ArrayBuffer(44+samples.length*2),view=new DataView(buffer);
    const write=(offset:number,value:string)=>{for(let i=0;i<value.length;i++)view.setUint8(offset+i,value.charCodeAt(i));};
    write(0,"RIFF");view.setUint32(4,36+samples.length*2,true);write(8,"WAVEfmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,16000,true);view.setUint32(28,32000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);write(36,"data");view.setUint32(40,samples.length*2,true);
    samples.forEach((sample,index)=>view.setInt16(44+index*2,Math.round(Math.max(-1,Math.min(1,sample))*32767),true));return buffer;
  }finally{await context.close();}
}
export default function AiMode(){
  const {id}=useParams(),navigate=useNavigate();
  const [status,setStatus]=useState<Status|null>(null),[session,setSession]=useState<Session|null>(null),[scenarios,setScenarios]=useState<{id:string;title:string}[]>([]),[presets,setPresets]=useState<Preset[]>([]),[presetName,setPresetName]=useState(""),[scenarioId,setScenarioId]=useState(""),[mode,setMode]=useState<"negotiation"|"interview">("negotiation"),[setup,setSetup]=useState<Setup>(initial),[text,setText]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false),[speak,setSpeak]=useState(()=>localStorage.getItem("arena-ai-speak")==="1");
  const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),stream=useRef<MediaStream|null>(null),recordTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  useEffect(()=>{api<Status>("/ai/status").then(setStatus).catch(e=>setError(e.message));api<{id:string;title:string}[]>("/scenarios").then(setScenarios).catch(()=>{});api<Preset[]>("/ai/presets").then(setPresets).catch(()=>{});},[]);
  useEffect(()=>{if(id)api<Session>(`/ai/sessions/${id}`).then(setSession).catch(e=>setError(e.message));},[id]);
  useEffect(()=>()=>{recorder.current?.state==="recording"&&recorder.current.stop();if(recordTimer.current)clearTimeout(recordTimer.current);stream.current?.getTracks().forEach(track=>track.stop());speechSynthesis.cancel();},[]);
  const change=(key:keyof Setup,value:string|number)=>setSetup(previous=>({...previous,[key]:value}));
  async function create(){setError("");setBusy(true);try{const result=await api<Session>("/ai/sessions","POST",{mode,...setup,...(mode==="negotiation"&&scenarioId?{scenarioId}:{})});navigate(`/ai/${result.id}`);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function savePreset(){if(!presetName.trim())return;try{const saved=await api<Preset>("/ai/presets","POST",{name:presetName.trim(),setup:{mode,...setup,...(scenarioId?{scenarioId}:{})}});setPresets(previous=>[saved,...previous]);setPresetName("");}catch(e){setError((e as Error).message)}}
  async function send(){if(!text.trim()||!session)return;setBusy(true);setError("");try{const result=await api<{reply:string;session:Session}>(`/ai/sessions/${session.id}/turn`,"POST",{text:text.trim()});setSession(result.session);setText("");if(speak&&"speechSynthesis" in window){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(result.reply);utterance.lang="ru-RU";speechSynthesis.speak(utterance);}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function finish(){if(!session)return;setBusy(true);try{setSession(await api<Session>(`/ai/sessions/${session.id}/finish`,"POST"));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function toggleRecord(){if(recording){recorder.current?.stop();setRecording(false);return;}try{const input=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=input;chunks.current=[];const media=new MediaRecorder(input);recorder.current=media;media.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};media.onstop=async()=>{if(recordTimer.current)clearTimeout(recordTimer.current);setRecording(false);input.getTracks().forEach(track=>track.stop());try{setBusy(true);setText(await transcribeWav(await toWav(new Blob(chunks.current))));}catch(e){setError((e as Error).message)}finally{setBusy(false)}};media.start();setRecording(true);recordTimer.current=setTimeout(()=>{if(media.state==="recording")media.stop()},20000);}catch(e){setError((e as Error).message)}}
  const finished=session?.status==="finished"||Boolean(session?.roomQuestions&&session.messages.filter(message=>message.role==="user").length>=session.roomQuestions.length);
  return <div className="page narrow"><Link className="back-link" to="/practice">← К практике</Link><span className="kicker">СВОБОДНЫЙ ДИАЛОГ</span><h1>Разговор с ИИ</h1>{error&&<p className="error" role="alert">{error}</p>}{status?.provider==="local-template"&&<p className="detail-panel">Внешняя модель не настроена: работает локальный шаблонный собеседник.</p>}
    {!id?<div className="detail-panel ai-setup"><p>Настройте ситуацию. Оценка текста ориентировочная и не проверяет факты или реальное согласие собеседника.</p>{presets.length>0&&<label className="field-label">Сохранённый пресет<select defaultValue="" onChange={e=>{const preset=presets.find(item=>item.id===e.target.value);if(preset){setMode(preset.setup.mode);setScenarioId(preset.setup.scenarioId??"");setSetup({...initial,...preset.setup});}}}><option value="">Выберите пресет</option>{presets.map(preset=><option key={preset.id} value={preset.id}>{preset.name}</option>)}</select></label>}<label className="field-label">Формат<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="negotiation">Переговоры</option><option value="interview">Собеседование</option></select></label>
      {mode==="negotiation"&&<label className="field-label">Ситуация<select value={scenarioId} onChange={e=>setScenarioId(e.target.value)}><option value="">Свободная тема</option>{scenarios.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>}
      {([ ["userName","Ваше имя"],["userRole","Ваша роль"],["opponentRole","Роль собеседника"],["problem","Проблема"],["goal","Желаемый результат"],...(mode==="interview"?[["company","Компания"],["position","Должность"]]:[]),["industry","Отрасль"],["companySize","Размер компании"],["culture","Культурный контекст"]] as [keyof Setup,string][]).map(([key,label])=><label className="field-label" key={key}>{label}<input value={String(setup[key])} onChange={e=>change(key,e.target.value)} maxLength={key==="problem"?1000:key==="goal"?500:150}/></label>)}
      <label className="field-label">Характер<select value={setup.character} onChange={e=>change("character",e.target.value)}><option value="neutral">Нейтральный</option><option value="supportive">Поддерживающий</option><option value="skeptical">Скептический</option><option value="demanding">Требовательный</option><option value="aggressive">Резкий</option></select></label>
      <label className="field-label">Ваш уровень<select value={setup.level} onChange={e=>change("level",e.target.value)}><option value="beginner">Начальный</option><option value="intermediate">Средний</option><option value="advanced">Продвинутый</option></select></label>
      <label className="field-label">Сложность: {setup.difficulty}<input type="range" min="1" max="5" value={setup.difficulty} onChange={e=>change("difficulty",Number(e.target.value))}/></label><label className="field-label">Имя пресета<input value={presetName} maxLength={80} onChange={e=>setPresetName(e.target.value)}/></label><div className="exercise-actions"><button className="button secondary" disabled={!presetName.trim()} onClick={savePreset}>Сохранить пресет</button><button className="button primary" disabled={busy} onClick={create}>Начать разговор</button></div></div>:session?<><div className="detail-panel"><h2>{session.mode==="interview"?"Собеседование":"Переговоры"}</h2>{session.provider&&<p>Источник: {session.provider}</p>}{session.messages.map((message,index)=><p key={index}><strong>{message.role==="user"?"Вы":"Собеседник"}: </strong>{message.content}</p>)}</div>
      {session.analysis?.at(-1)&&<div className="detail-panel"><h3>Последняя реплика</h3><p>{session.analysis.at(-1)?.comment}</p><p>{Object.entries(session.analysis.at(-1)!.metrics).map(([key,value])=>`${names[key as keyof Scores]} ${value}`).join(" · ")}</p></div>}
      {!finished&&<><label className="field-label">Ваша реплика<textarea rows={3} value={text} onChange={e=>setText(e.target.value)} maxLength={2000}/></label><div className="exercise-actions"><button className="button primary" disabled={busy||!text.trim()} onClick={send}>Отправить</button>{status?.voiceAvailable&&<button className="button secondary" disabled={busy} onClick={toggleRecord}>{recording?"Остановить запись":"🎙 Голосовой ввод"}</button>}{!session.roomId&&<button className="button secondary" disabled={busy} onClick={finish}>Завершить и получить отчёт</button>}</div></>}
      <label className="item-choice"><input type="checkbox" checked={speak} onChange={e=>{setSpeak(e.target.checked);localStorage.setItem("arena-ai-speak",e.target.checked?"1":"0");if(!e.target.checked)speechSynthesis.cancel()}}/><span>Озвучивать ответы, в том числе в текстовом чате</span></label>
      {session.report&&<div className="detail-panel"><h2>Итог: {session.report.verdict}</h2><p>{session.report.note}</p><p>{Object.entries(session.report.metrics).map(([key,value])=>`${names[key as keyof Scores]} ${value}`).join(" · ")}</p>{session.report.recommendations.map((item,index)=><p key={index}>{item}</p>)}</div>}
      {session.roomId&&<p><Link className="button secondary" to={`/rooms/${session.roomId}`}>К парному собеседованию →</Link></p>}</>:<div className="skeleton">Открываем диалог…</div>}</div>;
}
