import { useEffect, useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { api, transcribeWav } from "./api";

type Session={id:string;mode:"negotiation"|"interview";roomId?:string;roomQuestions?:string[];messages:{role:"user"|"assistant";content:string}[]};
type Status={available:boolean;provider:string|null;voiceAvailable:boolean};
async function toWav(blob:Blob) {
  const context=new AudioContext();
  try {
    const decoded=await context.decodeAudioData(await blob.arrayBuffer());
    const offline=new OfflineAudioContext(1,Math.ceil(decoded.duration*16000),16000);
    const source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start();
    const rendered=await offline.startRendering();const samples=rendered.getChannelData(0);
    const buffer=new ArrayBuffer(44+samples.length*2),view=new DataView(buffer);
    const write=(offset:number,value:string)=>{for(let i=0;i<value.length;i++)view.setUint8(offset+i,value.charCodeAt(i));};
    write(0,"RIFF");view.setUint32(4,36+samples.length*2,true);write(8,"WAVEfmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,16000,true);view.setUint32(28,32000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);write(36,"data");view.setUint32(40,samples.length*2,true);
    samples.forEach((sample,index)=>view.setInt16(44+index*2,Math.round(Math.max(-1,Math.min(1,sample))*32767),true));
    return buffer;
  }finally{await context.close();}
}
export default function AiMode(){
  const {id}=useParams();const navigate=useNavigate();const [status,setStatus]=useState<Status|null>(null),[session,setSession]=useState<Session|null>(null),[scenarios,setScenarios]=useState<{id:string;title:string}[]>([]),[scenarioId,setScenarioId]=useState(""),[text,setText]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false),[speak,setSpeak]=useState(()=>localStorage.getItem("arena-ai-speak")==="1");
  const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),stream=useRef<MediaStream|null>(null),recordTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  useEffect(()=>{api<Status>("/ai/status").then(setStatus).catch(e=>setError(e.message));api<{id:string;title:string}[]>("/scenarios").then(setScenarios).catch(()=>{});},[]);
  useEffect(()=>{if(id)api<Session>(`/ai/sessions/${id}`).then(setSession).catch(e=>setError(e.message));},[id]);
  useEffect(()=>()=>{recorder.current?.state==="recording"&&recorder.current.stop();if(recordTimer.current)clearTimeout(recordTimer.current);stream.current?.getTracks().forEach(track=>track.stop());speechSynthesis.cancel();},[]);
  async function create(mode:"negotiation"|"interview"){setError("");try{const result=await api<Session>("/ai/sessions","POST",{mode,...(mode==="negotiation"&&scenarioId?{scenarioId}:{})});navigate(`/ai/${result.id}`);}catch(e){setError((e as Error).message)}}
  async function send(){if(!text.trim()||!session)return;setBusy(true);setError("");try{const result=await api<{reply:string;session:Session}>(`/ai/sessions/${session.id}/turn`,"POST",{text:text.trim()});setSession(result.session);setText("");if(speak&&"speechSynthesis" in window){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(result.reply);utterance.lang="ru-RU";speechSynthesis.speak(utterance);}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function toggleRecord(){if(recording){recorder.current?.stop();setRecording(false);return;}try{const input=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=input;chunks.current=[];const media=new MediaRecorder(input);recorder.current=media;media.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};media.onstop=async()=>{if(recordTimer.current)clearTimeout(recordTimer.current);setRecording(false);input.getTracks().forEach(track=>track.stop());try{setBusy(true);const wav=await toWav(new Blob(chunks.current));setText(await transcribeWav(wav));}catch(e){setError((e as Error).message)}finally{setBusy(false)}};media.start();setRecording(true);recordTimer.current=setTimeout(()=>{if(media.state==="recording")media.stop()},20000);}catch(e){setError((e as Error).message)}}
  const finished=Boolean(session?.roomQuestions&&session.messages.filter(message=>message.role==="user").length>=session.roomQuestions.length);
  return <div className="page narrow"><Link className="back-link" to="/practice">← К практике</Link><span className="kicker">СВОБОДНЫЙ ДИАЛОГ</span><h1>Разговор с ИИ</h1>{error&&<p className="error" role="alert">{error}</p>}{status&&!status.available&&<div className="detail-panel">ИИ пока не настроен на сервере. Сценарные миссии доступны без него.</div>}{!id?<><p className="lead">Выберите переговоры или собеседование. Этот режим не влияет на метрики и награды сценарных миссий.</p><div className="detail-panel ai-setup"><label className="field-label">Ситуация для переговоров<select value={scenarioId} onChange={e=>setScenarioId(e.target.value)}><option value="">Свободная тема</option>{scenarios.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><div className="exercise-actions"><button className="button primary" disabled={!status?.available} onClick={()=>create("negotiation")}>Начать переговоры</button><button className="button secondary" disabled={!status?.available} onClick={()=>create("interview")}>Собеседование</button></div></div></>:session?<><div className="detail-panel"><h2>{session.mode==="interview"?"Собеседование":"Переговоры"}</h2>{session.messages.length?session.messages.map((message,index)=><p key={index}><strong>{message.role==="user"?"Вы":"Собеседник"}: </strong>{message.content}</p>):<p>Напишите первую реплику.</p>}</div><label className="field-label">Ваша реплика<textarea rows={3} disabled={finished} value={text} onChange={e=>setText(e.target.value)} maxLength={2000}/></label><div className="exercise-actions"><button className="button primary" disabled={busy||finished||!text.trim()} onClick={send}>Отправить</button>{status?.voiceAvailable&&<button className="button secondary" disabled={busy||finished} onClick={toggleRecord}>{recording?"Остановить запись":"🎙 Голосовой ввод"}</button>}</div><label className="item-choice"><input type="checkbox" checked={speak} onChange={e=>{setSpeak(e.target.checked);localStorage.setItem("arena-ai-speak",e.target.checked?"1":"0");if(!e.target.checked)speechSynthesis.cancel()}}/><span>Озвучивать ответы, в том числе в текстовом чате</span></label>{session.roomId&&<p><Link className="button secondary" to={`/rooms/${session.roomId}`}>К парному собеседованию →</Link></p>}{finished&&<p>Все четыре вопроса пройдены.</p>}</>:<div className="skeleton">Открываем диалог…</div>}</div>;
}
