import type { Metrics } from "@arena/contracts";

type Insight={metricHistory:Metrics[];tki:{style:string;count:number;percent:number}[];tkiTagged:number;techniques:string[];mistakes:{stepId:string;text:string;comment:string;alternative:string|null}[];preparedGoal:string;hiddenGoal?:{guessed:number|null;correctText:string;ok:boolean}|null;harvard?:{batna:boolean;objectiveCriteria:boolean;interests:boolean};recommendations?:string[];chaosHistory?:{eventId:string;text:string}[];pressureMisses?:number};
const labels:Record<keyof Metrics,string>={trust:"Доверие",goal:"Цель",control:"Контроль",eq:"EQ"};
const colors:Record<keyof Metrics,string>={trust:"#76c58c",goal:"#ffad48",control:"#8da7ff",eq:"#ef86ad"};
const keys=Object.keys(labels) as (keyof Metrics)[];
export default function OfflineInsights({assessment}:{assessment:Insight}){
  const count=assessment.metricHistory.length;
  return <div className="report-grid offline-insights"><section className="report-card"><h3>Как менялись показатели</h3><svg className="metric-chart" viewBox="0 0 480 220" role="img" aria-label="График четырёх показателей по ходам разговора">
    {[0,25,50,75,100].map(value=><g key={value}><line x1="35" x2="465" y1={190-value*1.65} y2={190-value*1.65} stroke="currentColor" opacity=".15"/><text x="4" y={194-value*1.65} fill="currentColor" fontSize="11">{value}</text></g>)}
    {keys.map(key=><polyline key={key} fill="none" stroke={colors[key]} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round" points={assessment.metricHistory.map((metrics,index)=>`${35+(count===1?0:index*430/(count-1))},${190-metrics[key]*1.65}`).join(" ")}/>)}
  </svg><div className="metric-legend">{keys.map(key=><span key={key}><i style={{background:colors[key]}}/>{labels[key]}</span>)}</div><small>Начальные значения и состояние после каждого выбранного хода.</small></section>
  <section className="report-card"><h3>Стили поведения</h3>{assessment.tkiTagged?assessment.tki.map(item=><div className="style-row" key={item.style}><span>{item.style}</span><strong>{item.percent}%</strong><div className="track"><span style={{width:`${item.percent}%`}}/></div></div>):<p>В этой попытке стили не размечены в исходном сценарии.</p>}<small>Доли считаются только по вариантам, которым автор сценария присвоил стиль TKI.</small>{assessment.techniques.length>0&&<p><strong>Использованные приёмы:</strong> {assessment.techniques.join(", ")}</p>}</section>
  <section className="report-card"><h3>Цель и решения</h3><p><strong>Ваша цель:</strong> {assessment.preparedGoal||"Не указана"}</p>{assessment.hiddenGoal&&<p><strong>Скрытая цель:</strong> {assessment.hiddenGoal.correctText}. {assessment.hiddenGoal.guessed===null?"Вы не выбрали гипотезу.":assessment.hiddenGoal.ok?"Вы угадали.":"Гипотеза не совпала."}</p>}{assessment.harvard&&<p>BATNA: {assessment.harvard.batna?"использована":"не отмечена"} · Объективные критерии: {assessment.harvard.objectiveCriteria?"есть":"не отмечены"} · Интересы: {assessment.harvard.interests?"обсуждались":"не отмечены"}</p>}{assessment.pressureMisses? <p>Превышено время ответов: {assessment.pressureMisses}</p>:null}{assessment.chaosHistory?.length?<p>Неожиданные события: {assessment.chaosHistory.map(item=>item.text).join("; ")}</p>:null}{assessment.mistakes.length?<><h4>Ходы, снизившие показатели</h4>{assessment.mistakes.map((item,index)=><div className="evidence" key={`${item.stepId}-${index}`}><b>{String(index+1).padStart(2,"0")}</b><div><strong>{item.text}</strong><p>{item.comment}</p>{item.alternative&&<small>Другой вариант: {item.alternative}</small>}</div></div>)}</>:<p>Ходов с отрицательным влиянием на показатели не было.</p>}{assessment.recommendations?.map((item,index)=><p key={index}>Совет: {item}</p>)}</section></div>;
}
