import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "./api";

type Person={id:string;email:string;relationship:"none"|"sent"|"received"|"friends"};
type Message={id:string;sender_id:string;text:string;created_at:string};
export default function People(){
  const [query,setQuery]=useState(""),[people,setPeople]=useState<Person[]>([]),[friends,setFriends]=useState<Person[]>([]),[selected,setSelected]=useState<Person|null>(null),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(""),[error,setError]=useState("");
  async function refresh(){try{const [p,f]=await Promise.all([api<Person[]>(`/people?q=${encodeURIComponent(query)}`),api<Person[]>("/friends")]);setPeople(p);setFriends(f);}catch(e){setError((e as Error).message)}}
  useEffect(()=>{refresh()},[query]);
  useEffect(()=>{if(!selected)return;let live=true;const read=()=>api<Message[]>(`/messages/${selected.id}`).then(data=>{if(live)setMessages(data)}).catch(()=>{});read();const timer=setInterval(read,2500);return()=>{live=false;clearInterval(timer)}},[selected?.id]);
  async function action(person:Person,kind:"request"|"accept"|"remove"){try{await api(`/friends/${person.id}${kind==="remove"?"":`/${kind}`}`,kind==="remove"?"DELETE":"POST");await refresh();if(kind==="remove")setSelected(null);}catch(e){setError((e as Error).message)}}
  async function send(){if(!selected||!draft.trim())return;try{await api(`/messages/${selected.id}`,"POST",{text:draft});setDraft("");setMessages(await api<Message[]>(`/messages/${selected.id}`));}catch(e){setError((e as Error).message)}}
  return <div className="page"><span className="kicker">СОВМЕСТНАЯ ПРАКТИКА</span><h1>Люди</h1><p className="lead">Найдите участника, добавьте в друзья и договоритесь о переговорах.</p><Link className="button primary" to="/rooms">Комнаты переговоров →</Link>{error&&<p className="error" role="alert">{error}</p>}<div className="conversation-grid"><div><h2>Поиск</h2><input aria-label="Поиск пользователей" placeholder="Логин или почта" value={query} onChange={e=>setQuery(e.target.value)}/><div className="learning-levels">{people.map(person=><div className="learning-level" key={person.id}><span><strong>{person.email}</strong><small>{person.relationship==="friends"?"В друзьях":person.relationship==="sent"?"Заявка отправлена":person.relationship==="received"?"Входящая заявка":""}</small></span>{person.relationship==="none"?<button className="button secondary" onClick={()=>action(person,"request")}>Добавить</button>:person.relationship==="received"?<button className="button secondary" onClick={()=>action(person,"accept")}>Принять</button>:person.relationship==="friends"?<button className="button secondary" onClick={()=>setSelected(person)}>Чат</button>:null}</div>)}</div></div><aside className="side-panel"><h2>Друзья</h2>{friends.filter(person=>person.relationship==="friends").map(person=><button className="learning-level" key={person.id} onClick={()=>setSelected(person)}>{person.email}</button>)}{selected&&<><h3>Чат: {selected.email}</h3><div className="people-chat">{messages.map(message=><p key={message.id}><strong>{message.sender_id===selected.id?selected.email:"Вы"}: </strong>{message.text}</p>)}</div><textarea aria-label="Сообщение другу" value={draft} onChange={e=>setDraft(e.target.value)} rows={2} maxLength={2000}/><button className="button primary" onClick={send}>Отправить</button><button className="button secondary" onClick={()=>action(selected,"remove")}>Удалить из друзей</button></>}</aside></div></div>;
}
