import { useEffect, useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { api } from "./api";
import { RoomPlanning } from "./RoomPlanning";

type Room={id:string;code:string;status:"waiting"|"scheduled"|"active"|"finished"|"cancelled"|"expired";mode:"human"|"duel";isHost:boolean;problem:string;goal?:string;yourRole:string;yourBrief:string;yourId:string;peerId:string|null;peerName:string|null;done:boolean;peerDone:boolean;deadline:string|null;scheduledAt:string|null;durationMinutes:number;ready:boolean;peerReady:boolean;messages:{id:string;user_id:string;text:string}[];yourSessionId:string|null;interviews?:{userId:string;name:string;messages:{role:string;content:string}[]}[];report?:{turns:number;participantTurns:Record<string,number>;feedback:Record<string,"agreement"|"no_agreement">;verdict:"agreement"|"no_agreement"|"disputed"|"not_assessed"}};
type Signal={cursor:number;kind:"offer"|"answer"|"candidate";data:Record<string,unknown>};

function PeerCall({room}:{room:Room}){
  const local=useRef<HTMLVideoElement>(null),remote=useRef<HTMLVideoElement>(null),pc=useRef<RTCPeerConnection|null>(null),stream=useRef<MediaStream|null>(null),cursor=useRef(0),pending=useRef<RTCIceCandidateInit[]>([]),recorder=useRef<MediaRecorder|null>(null),recordedUrlRef=useRef<string|null>(null);
  const [active,setActive]=useState(false),[error,setError]=useState(""),[recording,setRecording]=useState(false),[recordedUrl,setRecordedUrl]=useState<string|null>(null);
  useEffect(()=>()=>{if(recorder.current?.state==="recording")recorder.current.stop();pc.current?.close();stream.current?.getTracks().forEach(track=>track.stop());if(recordedUrlRef.current)URL.revokeObjectURL(recordedUrlRef.current)},[]);
  useEffect(()=>{if(!active)return;let live=true;const poll=async()=>{try{const signals=await api<Signal[]>(`/rooms/${room.id}/signals?after=${cursor.current}`);for(const signal of signals){cursor.current=Math.max(cursor.current,signal.cursor);const peer=pc.current;if(!peer)continue;if(signal.kind==="offer"&&!room.isHost){await peer.setRemoteDescription(signal.data as unknown as RTCSessionDescriptionInit);for(const candidate of pending.current)await peer.addIceCandidate(candidate);pending.current=[];await peer.setLocalDescription(await peer.createAnswer());await api(`/rooms/${room.id}/signals`,"POST",{kind:"answer",data:peer.localDescription?.toJSON()});}else if(signal.kind==="answer"&&room.isHost){await peer.setRemoteDescription(signal.data as unknown as RTCSessionDescriptionInit);for(const candidate of pending.current)await peer.addIceCandidate(candidate);pending.current=[];}else if(signal.kind==="candidate"){const candidate=signal.data as RTCIceCandidateInit;if(peer.remoteDescription)await peer.addIceCandidate(candidate);else pending.current.push(candidate);}}}catch(e){if(live)setError((e as Error).message)}};poll();const timer=setInterval(poll,1000);return()=>{live=false;clearInterval(timer)}},[active,room.id,room.isHost]);
  async function start(){try{const config=await api<RTCConfiguration>("/rooms/rtc-config");const media=await navigator.mediaDevices.getUserMedia({audio:true,video:true});stream.current=media;if(local.current)local.current.srcObject=media;const peer=new RTCPeerConnection(config);pc.current=peer;media.getTracks().forEach(track=>peer.addTrack(track,media));peer.ontrack=event=>{if(remote.current)remote.current.srcObject=event.streams[0]};peer.onicecandidate=event=>{if(event.candidate)api(`/rooms/${room.id}/signals`,"POST",{kind:"candidate",data:event.candidate.toJSON()}).catch(e=>setError(e.message))};setActive(true);if(room.isHost){await peer.setLocalDescription(await peer.createOffer());await api(`/rooms/${room.id}/signals`,"POST",{kind:"offer",data:peer.localDescription?.toJSON()});}}catch(e){setError((e as Error).message);pc.current?.close();stream.current?.getTracks().forEach(track=>track.stop());setActive(false)}}
  function startRecording(){try{if(!stream.current||typeof MediaRecorder==="undefined")throw Error("Запись не поддерживается этим браузером");const audio=new MediaStream(stream.current.getAudioTracks());const chunks:BlobPart[]=[];const instance=new MediaRecorder(audio);recorder.current=instance;instance.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};instance.onstop=()=>{if(recordedUrlRef.current)URL.revokeObjectURL(recordedUrlRef.current);const url=URL.createObjectURL(new Blob(chunks,{type:instance.mimeType||"audio/webm"}));recordedUrlRef.current=url;setRecordedUrl(url);setRecording(false)};instance.start(1000);setRecording(true)}catch(e){setError((e as Error).message)}}
  function stopRecording(){if(recorder.current?.state==="recording")recorder.current.stop()}
  function stop(){stopRecording();pc.current?.close();pc.current=null;stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;if(local.current)local.current.srcObject=null;if(remote.current)remote.current.srcObject=null;setActive(false)}
  return <div className="detail-panel"><h3>Видеосвязь</h3><div className="room-videos"><video ref={local} autoPlay muted playsInline aria-label="Ваше видео"/><video ref={remote} autoPlay playsInline aria-label="Видео собеседника"/></div>{(room.status==="active"||active)&&<button className="button secondary" onClick={active?stop:start}>{active?"Завершить звонок":"Включить камеру и микрофон"}</button>}{active&&<button className="button secondary" onClick={recording?stopRecording:startRecording}>{recording?"Остановить запись микрофона":"Записать свой микрофон"}</button>}{recordedUrl&&<a className="button secondary" href={recordedUrl} download={`my-voice-${room.code}.webm`}>Скачать свою запись</a>}<p>Запись остаётся в браузере до скачивания и не загружается на сервер.</p>{error&&<p className="error" role="alert">{error}</p>}</div>;
}

export function RoomsHub(){
  const navigate=useNavigate();const [rooms,setRooms]=useState<Room[]>([]),[problem,setProblem]=useState(""),[goal,setGoal]=useState(""),[mode,setMode]=useState<"human"|"duel">("human"),[aiAvailable,setAiAvailable]=useState(false),[code,setCode]=useState(""),[error,setError]=useState("");
  useEffect(()=>{api<Room[]>("/rooms").then(setRooms).catch(e=>setError(e.message));api<{externalAvailable:boolean}>("/ai/status").then(status=>setAiAvailable(status.externalAvailable)).catch(()=>{});},[]);
  async function create(){try{const room=await api<Room>("/rooms","POST",{mode,problem,goal});navigate(`/rooms/${room.id}`)}catch(e){setError((e as Error).message)}}
  async function join(){try{const room=await api<Room>("/rooms/join","POST",{code});navigate(`/rooms/${room.id}`)}catch(e){setError((e as Error).message)}}
  return <div className="page narrow"><Link className="back-link" to="/people">← К людям</Link><span className="kicker">1 × 1</span><h1>Парная практика</h1><p className="lead">Создайте комнату, передайте код другому пользователю и обсудите ситуацию за 15 минут.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="detail-panel"><h2>Новая комната</h2><label className="field-label">Формат<select value={mode} onChange={e=>setMode(e.target.value as "human"|"duel")}><option value="human">Парные переговоры</option><option value="duel" disabled={!aiAvailable}>Два независимых собеседования с ИИ</option></select></label>{!aiAvailable&&<p>Парное ИИ-собеседование появится после настройки ИИ-провайдера.</p>}<label className="field-label">Ситуация<textarea value={problem} onChange={e=>setProblem(e.target.value)} maxLength={1000} rows={3}/></label><label className="field-label">Ваша цель<input value={goal} onChange={e=>setGoal(e.target.value)} maxLength={500}/></label><button className="button primary" disabled={problem.trim().length<3||goal.trim().length<3} onClick={create}>Создать</button></div><div className="detail-panel"><h2>Войти по коду</h2><input aria-label="Код комнаты" value={code} onChange={e=>setCode(e.target.value)} maxLength={16}/><button className="button secondary" onClick={join}>Войти</button></div><h2>Мои комнаты</h2>{rooms.map(room=><Link className="history-item" key={room.id} to={`/rooms/${room.id}`}><strong>{room.problem}</strong><span>{room.status} →</span></Link>)}<Link className="button secondary" to="/rooms/demo">Посмотреть демонстрацию 1×1</Link><RoomPlanning/></div>;
}

function DuelRoom({room,onFinish,onCancel,error}:{room:Room;onFinish:()=>void;onCancel:()=>void;error:string}){
  return <div className="page narrow"><Link className="back-link" to="/rooms">← К комнатам</Link><span className="kicker">ПАРНОЕ СОБЕСЕДОВАНИЕ</span><h1>{room.problem}</h1>{error&&<p className="error" role="alert">{error}</p>}<div className="detail-panel"><p><strong>Код комнаты: </strong><code>{room.code}</code></p><p>{room.peerName?`Второй кандидат: ${room.peerName}`:"Передайте второму кандидату код комнаты."}</p><p>Каждый отвечает ИИ-интервьюеру отдельно. До завершения комнаты ответы другого участника скрыты.</p>{room.status==="active"&&room.yourSessionId&&<Link className="button primary" to={`/ai/${room.yourSessionId}`}>Открыть своё собеседование →</Link>}{room.status==="active"&&!room.done&&<button className="button secondary" onClick={onFinish}>Завершить свою попытку</button>}{room.done&&room.status!=="finished"&&<p>Ожидаем второго кандидата или окончания времени.</p>}{(room.status==="waiting"||room.status==="active")&&<button className="button secondary" onClick={onCancel}>Отменить комнату</button>}{(room.status==="cancelled"||room.status==="expired")&&<p>Комната закрыта без результата.</p>}</div>{room.status==="finished"&&<><h2>Ответы двух кандидатов</h2><p>Протоколы доступны обоим участникам для самостоятельного сравнения. Автоматическое решение о приёме пока не рассчитывается.</p><div className="report-grid">{room.interviews?.map(interview=><section className="report-card" key={interview.userId}><h3>{interview.name}</h3>{interview.messages.map((message,index)=><p key={index}><strong>{message.role==="user"?"Кандидат":"Интервьюер"}: </strong>{message.content}</p>)}</section>)}</div></>}</div>;
}

function DeviceCheck(){
  const [result,setResult]=useState("");
  async function check(){try{if(!navigator.mediaDevices?.enumerateDevices)throw Error("Браузер не предоставляет доступ к устройствам");const devices=await navigator.mediaDevices.enumerateDevices();setResult(`Микрофон: ${devices.some(device=>device.kind==="audioinput")?"найден":"не найден"}. Камера: ${devices.some(device=>device.kind==="videoinput")?"найдена":"не найдена"}. Доступ потребуется подтвердить при начале звонка.`)}catch(e){setResult((e as Error).message)}}
  return <div><button className="button secondary" onClick={check}>Проверить устройства</button>{result&&<p role="status">{result}</p>}</div>;
}
export function RoomPage(){
  const {id}=useParams();
  const [room,setRoom]=useState<Room|null>(null),[draft,setDraft]=useState(""),[error,setError]=useState(""),[now,setNow]=useState(Date.now()),[outcome,setOutcome]=useState<"agreement"|"no_agreement">("agreement");
  useEffect(()=>{let live=true;const load=()=>api<Room>(`/rooms/${id}`).then(data=>{if(live)setRoom(data)}).catch(e=>{if(live)setError(e.message)});load();const timer=setInterval(()=>{load();setNow(Date.now())},2000);return()=>{live=false;clearInterval(timer)}},[id]);
  async function refresh(path:string,body?:unknown){try{setRoom(await api<Room>(`/rooms/${id}/${path}`,"POST",body))}catch(e){setError((e as Error).message)}}
  async function send(){if(!draft.trim())return;try{await api(`/rooms/${id}/messages`,"POST",{text:draft});setDraft("");setRoom(await api<Room>(`/rooms/${id}`))}catch(e){setError((e as Error).message)}}
  function cancel(){if(window.confirm("Отменить комнату для обоих участников?"))void refresh("cancel")}
  const left=room?.deadline?Math.max(0,Math.ceil((new Date(room.deadline).getTime()-now)/1000)):0;
  if(room?.mode==="duel")return <DuelRoom room={room} onFinish={()=>void refresh("finish")} onCancel={cancel} error={error}/>;
  return <div className="page narrow"><Link className="back-link" to="/rooms">← К комнатам</Link>{error&&<p className="error" role="alert">{error}</p>}{!room?<div className="skeleton">Открываем комнату…</div>:<>
    <span className="kicker">ПАРНЫЕ ПЕРЕГОВОРЫ {room.status==="active"?`· ${Math.floor(left/60)}:${String(left%60).padStart(2,"0")}`:""}</span><h1>{room.problem}</h1>
    <div className="detail-panel"><p><strong>Код комнаты: </strong><code>{room.code}</code></p><p><strong>{room.yourRole}:</strong> {room.yourBrief}</p><p>{room.peerName?`Собеседник: ${room.peerName}`:"Ожидаем собеседника. Передайте ему код или отправьте приглашение."}</p>
      {room.scheduledAt&&<p>Начало: {new Intl.DateTimeFormat("ru-RU",{timeZone:"Europe/Moscow",dateStyle:"full",timeStyle:"short"}).format(new Date(room.scheduledAt))} МСК · {room.durationMinutes} минут</p>}
      {room.status==="scheduled"&&<><p>Готовность: вы — {room.ready?"готовы":"не готовы"}, партнёр — {room.peerReady?"готов":"не готов"}. Разговор начнётся, когда оба будут готовы и наступит время встречи.</p><DeviceCheck/>{!room.ready&&<button className="button primary" onClick={()=>void refresh("ready")}>Я готов(а)</button>}</>}
      {(room.status==="waiting"||room.status==="scheduled"||room.status==="active")&&<button className="button secondary" onClick={cancel}>Отменить комнату</button>}
      {(room.status==="cancelled"||room.status==="expired")&&<p>Комната закрыта без результата.</p>}
    </div>
    {(room.status==="active"||room.status==="finished")&&<PeerCall room={room}/>}
    {(room.status==="active"||room.status==="finished")&&<div className="detail-panel"><h2>Разговор</h2>{room.messages.length?room.messages.map(message=><p key={message.id}><strong>{message.user_id===room.yourId?"Вы":room.peerName}: </strong>{message.text}</p>):<p>Сообщений пока нет.</p>}
      {room.status==="active"&&!room.done&&<><textarea aria-label="Реплика в комнате" value={draft} onChange={e=>setDraft(e.target.value)} rows={3} maxLength={2000}/><div className="exercise-actions"><button className="button primary" disabled={!draft.trim()} onClick={send}>Отправить</button><label className="field-label">Ваш результат<select value={outcome} onChange={e=>setOutcome(e.target.value as "agreement"|"no_agreement")}><option value="agreement">Договорились</option><option value="no_agreement">Не договорились</option></select></label><button className="button secondary" onClick={()=>void refresh("finish",{outcome})}>Завершить свою часть</button></div></>}
      {room.done&&room.status!=="finished"&&<p>Ваша часть завершена. Ожидаем партнёра или окончания времени.</p>}
    </div>}
    {room.status==="finished"&&room.report&&<div className="detail-panel"><h2>Итог пары</h2><p>Реплик: {room.report.turns}. Ваших: {room.report.participantTurns[room.yourId]??0}. Партнёра: {room.peerId?room.report.participantTurns[room.peerId]??0:0}.</p><p>Итог: {({agreement:"Оба подтвердили договорённость",no_agreement:"Оба подтвердили отсутствие договорённости",disputed:"Оценки участников расходятся",not_assessed:"Оценок недостаточно"} as const)[room.report.verdict]}.</p><p>Отчёт основан на подтверждениях участников и числе реплик; автоматической оценки качества переговоров здесь нет.</p><button className="button secondary" onClick={()=>{const text=[room.problem,...room.messages.map(message=>`${message.user_id===room.yourId?"Вы":room.peerName}: ${message.text}`)].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"}));a.download=`room-${room.code}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}}>Скачать протокол</button></div>}
  </>}</div>;
}
