import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "./api";

type Item={code:string;name:string;category:"avatar"|"frame"|"theme";cost:number;minXp:number;requirements:string[];unlocked:boolean};
type Requirement={label:string;value:number;target:number;done:boolean};
export type Progression={xp:number;rank:string;rankLevel:number;nextRank:null|{xp:number;name:string;requirements:Requirement[]};stars:number;achievements:string[];achievementDetails:{code:string;name:string;stars:number;earnedAt:string}[];completed:number;levels:number;lessons:number;owned:string[];equipment:{avatar:string;frame:string;theme:string};catalog:Item[];ledger:{source:string;code:string;amount:number;created_at:string}[]};
export const avatarIcons:Record<string,string>={avatar_beginner:"✳",avatar_analyst:"◈",avatar_diplomat:"◇",avatar_manager:"▣",avatar_researcher:"⌕",avatar_mediator:"◎",avatar_hr:"✦",avatar_sales:"◆",avatar_negotiator:"✧",avatar_deal:"⬡",avatar_market:"◉",avatar_alternative:"↗",avatar_trust:"❖",avatar_sales_leader:"★",avatar_master:"✪",avatar_calm:"❋",avatar_trust_master:"✵",avatar_goal_master:"⬢"};
export function Shop(){
  const [data,setData]=useState<Progression|null>(null),[error,setError]=useState("");
  useEffect(()=>{api<Progression>("/progression").then(setData).catch(e=>setError(e.message))},[]);
  async function change(path:string,itemCode:string){try{const next=await api<Progression>(path,"POST",{itemCode});setData(next);window.dispatchEvent(new Event("arena-equipment-change"))}catch(e){setError((e as Error).message)}}
  return <div className="page"><Link className="back-link" to="/progress">← К прогрессу</Link><span className="kicker">НАГРАДЫ И ОФОРМЛЕНИЕ ПРОФИЛЯ</span><h1>Магазин и достижения</h1><p className="lead">Звёзды начисляются сервером за качество миссий, новые роли, достижения, ежедневное испытание и рубежи XP. Покупки и оформление сохраняются в аккаунте.</p>{error&&<p className="error" role="alert">{error}</p>}{!data?<div className="skeleton">Загружаем награды…</div>:<><div className="stat-grid"><div><span>ЗВЁЗДЫ</span><strong>{data.stars}</strong><small>доступно</small></div><div><span>РАНГ</span><strong>{data.rank}</strong><small>{data.xp} XP</small></div></div>{data.nextRank&&<div className="detail-panel"><h2>До ранга «{data.nextRank.name}»</h2>{data.nextRank.requirements.map(item=><p key={item.label}>{item.done?"✓":"○"} {item.label}: {item.value} / {item.target}</p>)}</div>}<div className="scenario-grid">{data.catalog.map(item=><div className="scenario-card" key={item.code}><div><span className="shop-preview">{item.category==="avatar"?avatarIcons[item.code]:item.category==="theme"?"◐":"▣"}</span><h2>{item.name}</h2><p>{item.category==="avatar"?"Значок":item.category==="frame"?"Рамка":"Тема профиля"} · {item.cost?`${item.cost} ★`:"Бесплатно"}</p>{item.requirements.length>0&&<p>Открыть: {item.requirements.join(", ")}</p>}</div><div className="scenario-bottom">{data.owned.includes(item.code)?<button className="button secondary" disabled={data.equipment[item.category]===item.code} onClick={()=>change("/shop/equip",item.code)}>{data.equipment[item.category]===item.code?"Выбрано":"Выбрать"}</button>:<button className="button primary" disabled={data.stars<item.cost||!item.unlocked} onClick={()=>change("/shop/purchase",item.code)}>Получить</button>}</div></div>)}</div><h2 className="section-title">Достижения</h2><div className="learning-levels">{data.achievementDetails.length?data.achievementDetails.map(item=><div className="learning-level" key={item.code}><span>★ {item.name}</span><small>+{item.stars} ★ · {new Date(item.earnedAt).toLocaleDateString("ru-RU")}</small></div>):<p>Первые достижения появятся после тренировки.</p>}</div><h2 className="section-title">История звёзд</h2>{data.ledger.map((item,index)=><div className="history-item" key={`${item.source}-${item.code}-${index}`}><span><strong>{item.source}: {item.code}</strong><small>{new Date(item.created_at).toLocaleString("ru-RU")}</small></span><strong>{item.amount>0?"+":""}{item.amount} ★</strong></div>)}</>}</div>;
}
