import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { api } from "./api";

type Node={id:string;type:"root"|"profession"|"skill"|"training"|"final";title:string;description?:string;parentId:string|null;state:"available"|"locked"|"completed";stars:number;lockedReason:string|null;current:number;total:number;round:null|{title:string;prompt:string;goal?:string;type:string;options:{id:string;text:string}[]};answers:{round:number;ok:boolean;feedback:string}[]};
export function SkillTree(){const [nodes,setNodes]=useState<Node[]>([]),[error,setError]=useState("");useEffect(()=>{api<{nodes:Node[]}>("/skills/tree").then(data=>setNodes(data.nodes)).catch(e=>setError(e.message))},[]);const children=(parentId:string)=>nodes.filter(node=>node.parentId===parentId);return <div className="page"><Link className="back-link" to="/path">← К пути развития</Link><span className="kicker">АРЕНА НАВЫКОВ</span><h1>Дерево навыков</h1><p className="lead">Выберите направление HR или Sales. Упражнения открываются по опыту и после предыдущего узла; финальная сцена использует обычную офлайн-миссию.</p>{error&&<p className="error" role="alert">{error}</p>}{children("root").map(profession=><section className="learning-chapter" key={profession.id}><h2>{profession.title}</h2><p>{profession.description}</p>{children(profession.id).map(skill=><div className="detail-panel" key={skill.id}><h3>{skill.title}</h3><p>{skill.description}</p><div className="learning-levels">{children(skill.id).map(node=><Link className={`learning-level ${node.state==="locked"?"is-locked":""}`} key={node.id} to={node.state==="locked"?"#":`/skills/${node.id}`} onClick={event=>{if(node.state==="locked")event.preventDefault()}}><span><strong>{node.title}</strong><small>{node.lockedReason??node.description}</small></span><span>{node.stars?`${"★".repeat(node.stars)}${"☆".repeat(3-node.stars)}`:node.state==="locked"?"🔒":"→"}</span></Link>)}</div></div>)}</section>)}</div>}
export function SkillNode(){
  const {id}=useParams(),navigate=useNavigate(),[node,setNode]=useState<Node|null>(null),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{api<Node>(`/skills/nodes/${id}`).then(setNode).catch(e=>setError(e.message))},[id]);
  async function start(){try{setNode(await api<Node>(`/skills/nodes/${id}/start`,"POST"));setFeedback("");setAnswer("")}catch(e){setError((e as Error).message)}}
  async function submit(body:{optionId?:string;answer?:string}){setBusy(true);try{const result=await api<{ok:boolean;feedback:string;node:Node}>(`/skills/nodes/${id}/answers`,"POST",body);setFeedback(result.feedback);setNode(result.node);if(result.ok)setAnswer("")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function final(){try{const result=await api<{sessionId:string}>(`/skills/finals/${id}/start`,"POST");navigate(`/sessions/${result.sessionId}`)}catch(e){setError((e as Error).message)}}
  return <div className="page narrow"><Link className="back-link" to="/skills">← К дереву навыков</Link>{error&&<p className="error" role="alert">{error}</p>}{!node?<div className="skeleton">Открываем узел…</div>:<><span className="kicker">{node.type==="final"?"ФИНАЛЬНАЯ СЦЕНА":"УПРАЖНЕНИЕ"}</span><h1>{node.title}</h1><p className="lead">{node.description}</p>{node.lockedReason&&<p className="error">{node.lockedReason}</p>}{node.type==="final"?<button className="button primary" disabled={node.state==="locked"} onClick={final}>Начать сценарий →</button>:<div className="detail-panel"><p>Раунд {Math.min(node.current+1,node.total)} из {node.total}. Лучший результат: {node.stars} из 3 звёзд.</p>{!node.round?<button className="button primary" disabled={node.state==="locked"} onClick={start}>{node.state==="completed"?"Повторить упражнение":"Начать упражнение"}</button>:<><h2>{node.round.title}</h2><p>{node.round.prompt}</p>{node.round.goal&&<p><strong>Задача: </strong>{node.round.goal}</p>}{node.round.options.length?<div className="learning-levels">{node.round.options.map(option=><button className="learning-level" key={option.id} disabled={busy} onClick={()=>submit({optionId:option.id})}>{option.text}</button>)}</div>:<><p>Ответ проверяется по ключевым приёмам, а не по смыслу целиком.</p><textarea aria-label="Ответ на упражнение" value={answer} onChange={e=>setAnswer(e.target.value)} rows={3} maxLength={1000}/><button className="button primary" disabled={busy||!answer.trim()} onClick={()=>submit({answer})}>Проверить</button></>}</>}{feedback&&<p role="status">{feedback}</p>}{node.current===node.total&&<p>Упражнение завершено. XP начислен один раз.</p>}</div>}</>}</div>;
}
