import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api } from "./api";

type Card={id:string;title:string;subtitle:string;duration_minutes:number;completed:boolean};
type Exercise={id:string;context:string;question:string;options:{id:string;text:string}[];result:null|{quality:number;feedback:string;explanation:string}};
type Lesson={id:string;title:string;subtitle:string;objectives:string[];sections:{title:string;body:string;example?:string;callout?:string}[];mistakes:string[];cheat_sheet:string[];practice:Exercise[];sources:{title:string;url:string;organization:string;note:string}[];answered:number;completed:boolean};
export function TheoryCatalog(){const [cards,setCards]=useState<Card[]>([]),[error,setError]=useState("");useEffect(()=>{api<Card[]>("/theory").then(setCards).catch(e=>setError(e.message))},[]);return <div className="page narrow"><Link className="back-link" to="/path">← К пути развития</Link><span className="kicker">ТЕОРИЯ И ПРАКТИКА</span><h1>Подготовка к переговорам</h1>{error&&<p className="error" role="alert">{error}</p>}<div className="learning-levels">{cards.map(card=><Link className="learning-level" to={`/theory/${card.id}`} key={card.id}><span><strong>{card.title}</strong><small>{card.subtitle} · {card.duration_minutes} минут</small></span><span>{card.completed?"✓":"→"}</span></Link>)}</div></div>}
export function TheoryLesson(){
  const {id}=useParams(),[lesson,setLesson]=useState<Lesson|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{api<Lesson>(`/theory/${id}`).then(setLesson).catch(e=>setError(e.message))},[id]);
  async function start(){try{setLesson(await api<Lesson>(`/theory/${id}/start`,"POST"))}catch(e){setError((e as Error).message)}}
  async function answer(exercise:Exercise,optionId:string){setBusy(true);try{const result=await api<{lesson:Lesson}>(`/theory/${id}/answers`,"POST",{exerciseId:exercise.id,optionId});setLesson(result.lesson)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function complete(){try{setLesson(await api<Lesson>(`/theory/${id}/complete`,"POST"))}catch(e){setError((e as Error).message)}}
  const current=lesson?.practice[lesson.answered];
  return <div className="page narrow"><Link className="back-link" to="/theory">← К урокам</Link>{error&&<p className="error" role="alert">{error}</p>}{!lesson?<div className="skeleton">Загружаем урок…</div>:<><span className="kicker">УРОК</span><h1 className="detail-title">{lesson.title}</h1><p className="lead">{lesson.subtitle}</p><div className="detail-panel"><h2>Чему научитесь</h2><ul>{lesson.objectives.map(item=><li key={item}>{item}</li>)}</ul></div>{lesson.sections.map((section,index)=><section className="detail-panel" key={index}><h2>{section.title}</h2><p>{section.body}</p>{section.example&&<p><strong>Пример: </strong>{section.example}</p>}{section.callout&&<p><strong>{section.callout}</strong></p>}</section>)}<div className="detail-panel"><h2>Памятка</h2><ul>{lesson.cheat_sheet.map(item=><li key={item}>{item}</li>)}</ul><h3>Частые ошибки</h3><ul>{lesson.mistakes.map(item=><li key={item}>{item}</li>)}</ul></div><div className="detail-panel"><h2>Проверка знаний</h2>{lesson.practice[0]?.options.length===0?<button className="button primary" onClick={start}>Начать упражнения</button>:lesson.completed?<p>Урок завершён. Ответы сохранены.</p>:current?<><p>Задание {lesson.answered+1} из {lesson.practice.length}</p><p>{current.context}</p><h3>{current.question}</h3><div className="learning-levels">{current.options.map(option=><button className="learning-level" key={option.id} disabled={busy} onClick={()=>answer(current,option.id)}>{option.text}</button>)}</div></>:<button className="button primary" onClick={complete}>Завершить урок · +15 XP</button>}{lesson.answered>0&&<p role="status"><strong>Последний ответ: </strong>{lesson.practice[lesson.answered-1].result?.feedback}</p>}</div><div className="detail-panel"><h2>Источники</h2>{lesson.sources.map(source=><p key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> · {source.organization}<br/>{source.note}</p>)}</div></>}</div>;
}
