"""company online rooms, competitions and program steps"""
from alembic import op
import sqlalchemy as sa
revision = "0016"
down_revision = "0015"
branch_labels = None
depends_on = None
def upgrade():
    op.create_table("company_program_steps", sa.Column("id",sa.Integer,primary_key=True),sa.Column("company_id",sa.Integer,sa.ForeignKey("companies.id"),nullable=False),sa.Column("program_id",sa.Integer,sa.ForeignKey("company_programs.id"),nullable=False),sa.Column("position",sa.Integer,nullable=False),sa.Column("title",sa.String(220),nullable=False),sa.Column("content_type",sa.String(32),nullable=False),sa.Column("assignment_id",sa.Integer,sa.ForeignKey("company_assignments.id")),sa.Column("unlock_rule",sa.String(32),nullable=False),sa.Column("min_score",sa.Integer),sa.Column("required",sa.Integer,nullable=False),sa.UniqueConstraint("program_id","position",name="uq_company_program_step_position"))
    op.create_table("company_room_bookings",sa.Column("id",sa.Integer,primary_key=True),sa.Column("company_id",sa.Integer,sa.ForeignKey("companies.id"),nullable=False),sa.Column("room_id",sa.Integer,sa.ForeignKey("arena_rooms.id"),nullable=False,unique=True),sa.Column("host_membership_id",sa.Integer,sa.ForeignKey("company_memberships.id"),nullable=False),sa.Column("guest_membership_id",sa.Integer,sa.ForeignKey("company_memberships.id"),nullable=False),sa.Column("title",sa.String(220),nullable=False),sa.Column("scheduled_at",sa.DateTime,nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("created_by",sa.Integer,sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime,server_default=sa.func.now()))
    op.create_table("company_competitions",sa.Column("id",sa.Integer,primary_key=True),sa.Column("company_id",sa.Integer,sa.ForeignKey("companies.id"),nullable=False),sa.Column("title",sa.String(220),nullable=False),sa.Column("assignment_id",sa.Integer,sa.ForeignKey("company_assignments.id")),sa.Column("kind",sa.String(24),nullable=False),sa.Column("starts_at",sa.DateTime),sa.Column("ends_at",sa.DateTime),sa.Column("status",sa.String(24),nullable=False),sa.Column("created_by",sa.Integer,sa.ForeignKey("users.id"),nullable=False))
    op.create_table("company_competition_participants",sa.Column("id",sa.Integer,primary_key=True),sa.Column("competition_id",sa.Integer,sa.ForeignKey("company_competitions.id"),nullable=False),sa.Column("membership_id",sa.Integer,sa.ForeignKey("company_memberships.id"),nullable=False),sa.Column("team_name",sa.String(120)),sa.UniqueConstraint("competition_id","membership_id",name="uq_company_competition_participant"))
    op.create_table("company_team_goals",sa.Column("id",sa.Integer,primary_key=True),sa.Column("company_id",sa.Integer,sa.ForeignKey("companies.id"),nullable=False),sa.Column("title",sa.String(220),nullable=False),sa.Column("target_score",sa.Integer,nullable=False),sa.Column("department_id",sa.Integer,sa.ForeignKey("company_departments.id")),sa.Column("deadline",sa.DateTime),sa.Column("status",sa.String(24),nullable=False),sa.Column("created_by",sa.Integer,sa.ForeignKey("users.id"),nullable=False))
def downgrade():
    op.drop_table("company_team_goals");op.drop_table("company_competition_participants");op.drop_table("company_competitions");op.drop_table("company_room_bookings");op.drop_table("company_program_steps")
