import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { apiSpeech } from "../api.js";

const labels = ["Как входит участник", "Напоминание", "Лобби", "Разговор", "Зал ожидания", "Отчёт"];

function WaveText({ text, instant }) {
  return <span className="wave-text" aria-label={text}>{text.split(/\s+/).map((word, index) => <span aria-hidden="true" className={instant ? "settled" : "wave-word"} style={{ animationDelay: `${Math.min(index * 65, 1800)}ms` }} key={`${word}-${index}`}>{word}&nbsp;</span>)}</span>;
}

export default function GuidedDemo() {
  const nav = useNavigate();
  const config = useMemo(() => JSON.parse(sessionStorage.getItem("arena_guided_demo") || "null"), []);
  const [step, setStep] = useState(0); const [instant, setInstant] = useState(false); const [notifications, setNotifications] = useState(false);
  const [ready, setReady] = useState(false); const [messages, setMessages] = useState([]); const [text, setText] = useState("");
  const [duration, setDuration] = useState(3); const [seconds, setSeconds] = useState(180);
  const [listening, setListening] = useState(false);
  const guest = config?.mode === "duel" ? "Антон, демо-напарник" : "Антон, ИИ в роли второй стороны";
  const scenario = config?.request_text || "Учебные переговоры";
  const greeting = config?.mode === "duel" ? `Здравствуйте, ${config?.display_name}. Начнём учебное собеседование по теме «${scenario}». Кратко представьтесь и расскажите, почему вам интересна эта роль.` : `Здравствуйте. Мы встретились, чтобы обсудить ситуацию «${scenario}». Изложите, пожалуйста, ваше предложение.`;
  const meeting = config?.scheduled_at ? new Date(config.scheduled_at) : new Date(Date.now() + 10 * 60 * 1000);

  async function speak(value) { try { const blob = await apiSpeech("/api/rooms/demo/speak", value); const audio = new Audio(URL.createObjectURL(blob)); await audio.play(); } catch { /* text remains available when autoplay or TTS is unavailable */ } }
  useEffect(() => { if (step === 3 && ready && !messages.length) { setMessages([{ from: "ai", text: greeting }]); speak(greeting); } }, [step, ready]);
  useEffect(() => { if (step !== 3 || !ready) return; const timer = setInterval(() => setSeconds((value) => { if (value <= 1) { clearInterval(timer); return 0; } return value - 1; }), 1000); return () => clearInterval(timer); }, [step, ready]);
  useEffect(() => { if (seconds === 60 && !messages.some((item) => item.wrap)) setMessages((items) => [...items, { from: "ai", wrap: true, text: "Спасибо, я вас услышал. У нас осталась одна минута: добавьте главное, что ещё важно учесть, после чего перейдём в зал ожидания." }]); }, [seconds]);
  useEffect(() => { if (step === 3 && seconds === 0) { setMessages((items) => [...items, { from: "ai", text: "Хорошо, я вас услышал. Пожалуйста, перейдите в зал ожидания — результат будет готов через пару минут." }]); setTimeout(() => setStep(4), 1200); } }, [seconds, step]);
  if (!config) return <div className="glass mx-auto max-w-xl rounded-3xl p-7"><h1 className="text-2xl font-bold">Настройки демо не найдены</h1><button className="primary-button mt-4" onClick={() => nav("/rooms")}>Вернуться к настройке</button></div>;

  function send(raw = text) { const value = raw.trim(); if (!value) return; const count = messages.filter((item) => item.from === "user").length; const replies = config.mode === "duel" ? ["Спасибо. Приведите конкретный пример результата, которого вы добились.", "Как вы действовали, когда требования были неполными или менялись?", "Расскажите о сложном рабочем разногласии и вашем решении.", "Что вы сделаете в первые недели на этой позиции?"] : ["Что в вашем предложении важно для второй стороны?", "На какие условия вы готовы пойти, а какие для вас принципиальны?", "Какими фактами вы подтверждаете свою позицию?", "Какой вариант соглашения вы считаете справедливым?"]; const reply = replies[Math.min(count, replies.length - 1)]; setMessages((items) => [...items, { from: "user", text: value }, { from: "ai", text: reply }]); setText(""); speak(reply); }
  function listen() { const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Recognition) { alert("В этом браузере голосовой ввод недоступен. Используйте текстовое поле."); return; } const recognition = new Recognition(); recognition.lang = "ru-RU"; recognition.interimResults = true; setListening(true); recognition.onresult = (event) => { const value = [...event.results].map((item) => item[0].transcript).join(" "); setText(value); if (event.results[event.results.length - 1].isFinal) send(value); }; recognition.onerror = () => setListening(false); recognition.onend = () => setListening(false); recognition.start(); }
  function next() { setStep((value) => Math.min(5, value + 1)); }
  const time = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
  return <div className="mx-auto max-w-6xl space-y-5 pb-24"><header className="glass sticky top-2 z-30 flex flex-wrap items-center gap-3 rounded-3xl p-4"><span className="rounded-full bg-violet-400/15 px-3 py-1 text-xs font-bold tracking-widest text-violet-200">ДЕМОНСТРАЦИЯ</span><b className="min-w-0 flex-1 truncate">{scenario}</b><button className="subtle-button text-sm" onClick={() => setNotifications(!notifications)}>🔔 Уведомления {step >= 1 ? "1" : ""}</button><button className="text-sm text-slate-400" onClick={() => nav("/rooms")}>Выйти</button>{notifications && <div className="absolute right-4 top-16 z-40 w-[min(360px,calc(100vw-2rem))] rounded-2xl border border-white/10 bg-slate-950 p-4 shadow-2xl"><b>Встреча через 5 минут</b><p className="mt-2 text-sm text-slate-300">Демо-встреча «{scenario}» готова.</p><button className="primary-button mt-3 text-sm" onClick={() => { setStep(2); setNotifications(false); }}>Перейти в лобби</button></div>}</header>
    <div className="hidden grid-cols-6 gap-2 md:grid">{labels.map((label, index) => <div className={`rounded-xl border p-2 text-center text-xs ${index === step ? "border-cyan-300 bg-cyan-300/10 text-cyan-100" : index < step ? "border-emerald-300/20 text-emerald-200" : "border-white/10 text-slate-500"}`} key={label}>{index + 1}. {label}</div>)}</div><div className="text-sm text-slate-400 md:hidden">Шаг {step + 1} из {labels.length}: {labels[step]}</div>
    {step === 0 && <section className="glass rounded-3xl p-6"><div className="space-y-3"><p className="rounded-2xl bg-white/5 p-4">Покажем весь путь встречи. Вам не нужно приглашать второго человека и ждать назначенной даты.</p><p className="rounded-2xl bg-white/5 p-4">Представим, что ваш код получил другой участник. Это <b>{guest}</b>. Второй реальный человек в демонстрации не участвует.</p></div><div className="mt-6 rounded-3xl border border-cyan-300/20 bg-slate-950/60 p-5"><div className="text-xs uppercase tracking-widest text-cyan-300">ТАК ВИДИТ ПРИГЛАШЕНИЕ ВТОРОЙ УЧАСТНИК</div><DemoField label="Код комнаты" value="DEMO-7Q4K" instant={instant}/><DemoField label="Тема" value={scenario} instant={instant}/><DemoField label="Создатель" value={config.display_name} instant={instant}/><DemoField label="Имя участника" value="Антон · Демо-участник" instant={instant}/><DemoField label="Роль" value={config.mode === "duel" ? "Кандидат" : "Вторая сторона переговоров"} instant={instant}/><div className="mt-4 rounded-xl bg-emerald-400/10 p-3 text-emerald-200">✓ Демо-участник присоединился</div></div></section>}
    {step === 1 && <section className="glass rounded-3xl p-7"><div className="eyebrow">ВИРТУАЛЬНОЕ ВРЕМЯ</div><h2 className="mt-2 text-3xl font-bold">До встречи осталось 5 минут</h2><p className="mt-3 text-slate-300">Представим, что сегодня {meeting.toLocaleString("ru-RU", { timeZone: "Europe/Moscow", weekday: "long", day: "numeric", month: "long", hour: "2-digit", minute: "2-digit" })} МСК. Вам обоим пришло уведомление.</p><div className="mt-5 rounded-2xl border border-violet-300/20 bg-violet-400/10 p-4"><b>🔔 Встреча скоро начнётся</b><p className="mt-1 text-sm">Перейдите по ссылке в лобби и проверьте микрофон.</p><button className="subtle-button mt-3" onClick={() => setStep(2)}>Открыть ссылку</button></div></section>}
    {step === 2 && <section className="grid gap-5 lg:grid-cols-[1fr_340px]"><div className="glass rounded-3xl p-7"><div className="eyebrow">ЛОББИ · ДЕМО</div><h2 className="mt-2 text-2xl font-bold">Ваше задание</h2><p className="mt-4 leading-relaxed text-slate-300">Вы — {config.role || (config.mode === "duel" ? "кандидат" : "инициатор переговоров")}. Ваша цель: {config.goal}. Профиль: {config.specialization || "общая практика"}, уровень — {config.level}.</p><div className="mt-5 rounded-2xl border border-white/10 p-4"><b>{guest}</b><p className="mt-1 text-sm text-slate-400">Вымышленный профиль для показа. Приватные данные реального пользователя не используются.</p></div></div><aside className="glass rounded-3xl p-5"><b>Длительность демо</b><div className="mt-3 grid gap-2"><button className={`rounded-xl border p-3 ${duration === 3 ? "border-cyan-300 bg-cyan-300/10" : "border-white/10"}`} onClick={() => { setDuration(3); setSeconds(180); }}>Короткое демо — 3 минуты</button><button className={`rounded-xl border p-3 ${duration === config.duration_minutes ? "border-cyan-300 bg-cyan-300/10" : "border-white/10"}`} onClick={() => { setDuration(config.duration_minutes); setSeconds(config.duration_minutes * 60); }}>Как встреча — {config.duration_minutes} минут</button></div><label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={ready} onChange={(e) => setReady(e.target.checked)}/>Микрофон проверен, задание понятно</label><button className="primary-button mt-4" disabled={!ready} onClick={() => setStep(3)}>Я готов — войти</button></aside></section>}
    {step === 3 && <section className="glass rounded-3xl p-5"><div className="flex items-center justify-between"><div><div className="eyebrow">ДЕМО-РАЗГОВОР</div><b>ИИ в роли собеседника · Онлайн</b></div><span className="font-mono text-2xl text-cyan-200">{time}</span></div><div className="mt-5 h-[390px] space-y-3 overflow-y-auto rounded-2xl bg-slate-950/60 p-4">{messages.map((item, index) => <div key={index} className={`flex ${item.from === "user" ? "justify-end" : "justify-start"}`}><div className={`max-w-[80%] rounded-2xl p-4 ${item.from === "user" ? "bg-cyan-300/15" : "bg-white/5"}`}><small className="text-slate-500">{item.from === "user" ? "Вы" : "Демо-собеседник"}</small><p className="mt-1">{item.text}</p></div></div>)}</div><div className="mt-3 flex gap-2"><button className={`rounded-xl border px-4 ${listening ? "border-rose-300 bg-rose-400/10 text-rose-200" : "border-cyan-300/30 text-cyan-100"}`} onClick={listen}>{listening ? "● Слушаю" : "◉ Голос"}</button><input className="min-w-0 flex-1 rounded-xl bg-slate-950 p-3" value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => e.key === "Enter" && send()} placeholder="Ответьте голосом или текстом…"/><button className="primary-button" onClick={() => send()}>Отправить</button></div><button className="mt-4 text-sm text-rose-200 underline" onClick={() => setStep(4)}>Завершить раньше и выйти в зал ожидания</button></section>}
    {step === 4 && <section className="glass rounded-3xl p-7 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-cyan-300/10 text-2xl">⌛</div><h2 className="mt-4 text-3xl font-bold">Зал ожидания</h2><p className="mt-3 text-slate-400">Диалог остановлен. Формируем две интерпретации одного и того же разговора.</p><div className="mx-auto mt-5 max-w-lg rounded-2xl border border-white/10 p-4 text-left"><b>{config.display_name}</b><p className="text-sm text-slate-400">{config.role || "Участник"} · {messages.filter((item) => item.from === "user").length} ответов</p><b className="mt-3 block">{guest}</b><p className="text-sm text-slate-400">Учебный собеседник; его результат не подменяет ваш.</p></div><button className="primary-button mt-6" onClick={() => setStep(5)}>Открыть разбор</button></section>}
    {step === 5 && <DemoReport config={config} answers={messages.filter((item) => item.from === "user")}/>} 
    {step < 2 && <footer className="fixed inset-x-0 bottom-0 z-20 border-t border-white/10 bg-slate-950/95 p-3 backdrop-blur"><div className="mx-auto flex max-w-6xl justify-end gap-3"><button className="subtle-button" onClick={() => setInstant(true)}>Показать заполненное</button><button className="primary-button" onClick={next}>Далее →</button></div></footer>}
  </div>;
}

function DemoField({ label, value, instant }) { return <div className="mt-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 min-h-12 select-text rounded-xl border border-white/10 bg-white/[.03] p-3"><WaveText text={value || "Не указано"} instant={instant}/></div></div>; }
function DemoReport({ config, answers }) { const enough = answers.length >= 3; return <section className="space-y-5"><div className="glass rounded-3xl p-7"><div className="eyebrow">ДЕМО-ОТЧЁТ</div><h2 className="mt-2 text-3xl font-bold">Один разговор — две политики оценки</h2><p className="mt-3 text-slate-400">Обе карточки используют только ваши {answers.length} ответов. Учебный результат не попадает в рейтинг и профильную статистику.</p></div><div className="grid gap-5 md:grid-cols-2"><article className="glass rounded-3xl border-emerald-300/20 p-6"><div className="text-xs text-emerald-300">СРЕДНЯЯ СТРОГОСТЬ</div><h3 className="mt-2 text-2xl font-bold">{enough ? "Условно пройдено" : "Недостаточно данных"}</h3><p className="mt-3 text-slate-300">Учитывает понятность позиции, мотивацию и способность привести хотя бы один конкретный пример.</p><ul className="mt-4 space-y-2 text-sm text-slate-400"><li>• Сильная сторона: цель сформулирована заранее.</li><li>• Улучшить: добавлять измеримые результаты и факты.</li></ul></article><article className="glass rounded-3xl border-rose-300/20 p-6"><div className="text-xs text-rose-300">ВЫСОКАЯ СТРОГОСТЬ</div><h3 className="mt-2 text-2xl font-bold">{answers.length >= 5 ? "Условно пройдено" : "Пока не пройдено"}</h3><p className="mt-3 text-slate-300">Требует нескольких проверяемых примеров, работы с рисками и ясного плана следующих шагов.</p><ul className="mt-4 space-y-2 text-sm text-slate-400"><li>• Не хватает подтверждённых результатов.</li><li>• Нужны ответы на возражения и конкретные условия.</li></ul></article></div><div className="glass rounded-3xl p-6"><b>Это учебная демонстрация</b><p className="mt-2 text-sm text-slate-400">Второго участника заменял ИИ. Уведомление и перенос времени были смоделированы. Реальная бронь, письмо, награда и рейтинговый результат не создавались.</p><button className="primary-button mt-5" onClick={() => location.assign("/rooms")}>Создать настоящую встречу</button></div></section>; }
