import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { api } from "../api.js";

const typeLabels = { RECOGNIZE: "Распознайте сигнал", FIND_MISTAKE: "Найдите ошибку", CHOICE: "Выберите ответ", COMPARE: "Сравните подходы", NEXT_MOVE: "Выберите следующий шаг", APPLY: "Примените навык", ASSUMPTION_CHECK: "Проверьте предположение", SUMMARIZE: "Соберите главное", SEQUENCE: "Выстройте последовательность", GUIDED_RESPONSE: "Сформулируйте ответ", COMBINED: "Комплексное задание" };

export default function PathSession() {
  const { attemptId } = useParams(); const nav = useNavigate(); const [data, setData] = useState(null); const [selected, setSelected] = useState(null); const [feedback, setFeedback] = useState(null); const [error, setError] = useState(""); const [sending, setSending] = useState(false);
  useEffect(() => { api(`/api/learning-path/attempts/${attemptId}`).then((result) => { if (result.status === "completed") nav(`/training/path/attempt/${attemptId}/report`, { replace: true }); else setData(result); }).catch((e) => setError(e.message)); }, [attemptId, nav]);
  if (error) return <p className="text-rose-300">{error}</p>; if (!data) return <p className="text-slate-400">Загружаем упражнение…</p>;
  const index = data.answers.length; const item = data.exercises[index];
  const submit = async () => { if (!selected) return; setSending(true); try { const result = await api(`/api/learning-path/attempts/${attemptId}/answers`, { method: "POST", body: { exercise_id: item.id, option_id: selected.id } }); setFeedback(result); } catch (e) { setError(e.message); } finally { setSending(false); } };
  const next = () => { if (feedback.finished) nav(`/training/path/attempt/${attemptId}/report`, { replace: true }); else { setData({ ...data, answers: [...data.answers, feedback.answer] }); setSelected(null); setFeedback(null); } };
  const exit = async () => { if (!window.confirm("Выйти из уровня? Незавершённая попытка не будет засчитана.")) return; await api(`/api/learning-path/attempts/${attemptId}/exit`, { method: "POST" }); nav(`/training/path/chapter/${data.level.chapter_id}`); };
  return <section className="path-session"><div className="session-head"><button onClick={exit} aria-label="Выйти из уровня">← Выйти</button><span>Глава {data.level.chapter_id === "chapter-1" ? 1 : 2} · Уровень {data.level.order}</span><b>Задание {index + 1} из {data.exercises.length}</b></div><div className="session-progress"><i style={{ width: `${(index / data.exercises.length) * 100}%` }} /></div><article className="exercise-card glass"><div className="exercise-type">{typeLabels[item.type] || "Задание"}</div>{item.context && <div className="exercise-context"><b>Ситуация</b><p>{item.context}</p></div>}<h1>{item.question}</h1><div className="exercise-options">{item.options.map((option) => <button disabled={Boolean(feedback)} className={`answer-button ${selected?.id === option.id ? "selected" : ""}`} onClick={() => setSelected(option)} key={option.id}>{option.text}</button>)}</div>{feedback ? <div className={`choice-feedback ${feedback.answer.quality}`}><b>{feedback.answer.quality === "strong" ? "Сильный ход" : feedback.answer.quality === "acceptable" ? "Рабочий вариант" : "Есть риск"}</b><p>{feedback.answer.feedback}</p><button className="primary-button" onClick={next}>{feedback.finished ? "Завершить уровень" : "Продолжить"}</button></div> : <button className="primary-button mt-6" disabled={!selected || sending} onClick={submit}>{sending ? "Проверяем…" : "Ответить"}</button>}</article></section>;
}
