import { Link } from "react-router-dom";

export default function PracticeGuide() {
  return <div className="practice-page practice-guide"><header className="practice-intro"><h1>Репетиция, из которой понятно, что взять в жизнь</h1></header>
    <section className="practice-guide-section"><div><h2>Сформулируйте желаемый результат</h2><p>Укажите роли, цель и ограничения разговора.</p><Link to="/ai/prepare">Настроить свою ситуацию →</Link></div><article className="practice-example-card"><h3>Перенести срок проекта</h3><dl><dt>Вы</dt><dd>Руководитель проекта</dd><dt>Собеседник</dt><dd>Заказчик</dd><dt>Результат</dt><dd>Дополнительная неделя на запуск</dd><dt>Ограничение</dt><dd>Без увеличения бюджета</dd></dl></article></section>
    <section className="practice-guide-section"><div><h2>Проверьте подход в диалоге</h2><p>Отвечайте текстом или голосом. Ментор поможет подобрать аргумент или улучшить реплику.</p></div><article className="practice-example-card practice-example-dialogue"><blockquote><b>Заказчик</b>Нам важно запуститься в пятницу. Почему нужно переносить всё?</blockquote><blockquote className="own"><b>Вы</b>Для вас важнее дата или полный объём функций?</blockquote><blockquote><b>Заказчик</b>Дата. Основные функции должны работать к показу.</blockquote></article></section>
    <section className="practice-guide-section"><div><h2>Посмотрите разбор</h2><p>Отчёт покажет важные реплики и следующий шаг. Разговор останется в истории.</p><Link to="/report/example">Открыть пример разбора →</Link></div><article className="practice-example-card"><h3>Вы выяснили интерес за требованием</h3><p>Вопрос о дате и объёме помог увидеть вариант: запустить основные функции в пятницу, остальные — через неделю.</p></article></section>
    <section className="practice-status-panel"><h2>Хотите потренировать собеседование?</h2><p>Укажите должность и уровень. ИИ задаст вопросы, а разбор покажет ваши аргументы и примеры.</p><div className="practice-actions"><Link className="primary-button" to="/ai/prepare">Настроить переговоры</Link><Link className="subtle-button" to="/ai/prepare?kind=job">Потренировать интервью</Link></div></section>
  </div>;
}
