import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../api.js";
import MetricsBar from "../MetricsBar.jsx";
import SocialProfile from "../components/SocialProfile.jsx";

const CTA = {
  "Пройти сценарий": "/scenarios", "Выбрать сценарий": "/scenarios", "Укрепить доверие": "/training/path", "Перейти к обучению": "/training/path", "Попробовать новую роль": "/setup", "Открыть новый сценарий": "/scenarios", "Изучить альтернативы": "/training/path", "Повторить тренировку": "/training/path", "Пройти сложный сценарий": "/scenarios", "Выбрать сложного оппонента": "/setup", "Выбрать новый тип конфликта": "/scenarios", "Завершить обучение": "/training/path",
};

export default function Profile() {
  const [profile, setProfile] = useState(null);
  const [error, setError] = useState("");
  const [achievementTab, setAchievementTab] = useState("earned");
  const [showAllEarned, setShowAllEarned] = useState(false);
  const nav = useNavigate();
  const load = () => api("/api/profile").then(setProfile);
  useEffect(() => { load().catch((cause) => setError(cause.message)); }, []);
  if (!profile && error) return <div className="glass report-load-state" role="alert"><h1>Профиль не открылся</h1><p>{error}</p><button className="primary-button" onClick={() => { setError(""); load().catch((cause) => setError(cause.message)); }}>Повторить</button></div>;
  if (!profile) return <div className="text-slate-400">Загружаем профиль…</div>;
  const last = profile.metrics_chart?.at(-1);
  const initials = profile.username.slice(0, 2).toUpperCase();
  const memberSince = profile.member_since ? new Date(`${profile.member_since}T00:00:00`).toLocaleDateString("ru-RU") : null;

  return <div id="profile-page" className={`profile-theme-${profile.cosmetics?.profile_theme || "theme_arena"} mx-auto max-w-7xl space-y-6`}>
    <section className="glass profile-intro profile-identity"><div className="profile-identity-row"><button title="Открыть магазин" onClick={() => nav("/shop")} className="profile-avatar profile-identity-avatar">{initials}<span>{profile.rank}</span></button><div className="profile-identity-copy"><div className="eyebrow">ЛИЧНЫЙ ПРОФИЛЬ</div><h1>{profile.username}</h1><p>{profile.rank_name} · ранг {profile.rank}</p>{profile.workspaces?.[0] && <small>🏢 {profile.workspaces[0].company} · {[profile.workspaces[0].department, profile.workspaces[0].job_title].filter(Boolean).join(" · ")}</small>}{memberSince && <small>В Арене с {memberSince} · серия {profile.current_streak} дн.</small>}</div><div className="profile-identity-stats"><Stat value={`★ ${profile.stars}`} label="Звёзды" /><Stat value={profile.xp} label="XP обучения" /></div></div></section>

    <SocialProfile profile={profile} onSaved={load} />

    <div className="grid gap-6 lg:grid-cols-12"><section className="glass rounded-3xl p-6 lg:col-span-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="eyebrow">СЛЕДУЮЩАЯ ВЕХА</div><h2 className="mt-1 text-2xl font-bold">{profile.next_rank_name ? `До ранга «${profile.next_rank_name}»` : "Максимальный ранг достигнут"}</h2></div><div className="text-right"><b className="text-2xl text-cyan-200">{profile.rank_progress}%</b><div className="text-xs text-slate-400">визуальный прогресс</div></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-violet-400" style={{ width: `${profile.rank_progress}%` }} /></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{(profile.rank_requirements || []).map((item) => <button key={item.label} onClick={() => !item.done && nav(CTA[item.cta] || "/setup")} className={`rank-requirement ${item.done ? "done" : ""}`}><span>{item.done ? "✓" : "◐"}</span><div><b>{item.label}</b><small>{item.value}</small></div>{!item.done && <em>{item.cta} →</em>}</button>)}</div></section>
      <section className="glass rounded-3xl p-6 lg:col-span-7"><div><div className="eyebrow">ПРОФИЛЬ ПРАКТИКИ</div><h2 className="mt-1 text-xl font-bold">Как вы ведёте переговоры <Info text="Это учебный профиль переговорного поведения по тренировкам и добровольному тесту; он не является психологическим диагнозом." /></h2></div><NegotiationProfile analysis={profile.negotiation_profile} onSaved={load} /><div className="mt-5 grid grid-cols-3 gap-3"><Mini label="Сессии" value={profile.sessions_total} /><Mini label="Роли" value={profile.unique_roles?.length || 0} /><Mini label="Сценарии" value={profile.unique_scenarios?.length || 0} /></div>{last && <div className="mt-6"><MetricsBar metrics={last} /></div>}</section>
      <section className="glass rounded-3xl p-6 lg:col-span-5"><div className="eyebrow">ОБУЧЕНИЕ</div><h2 className="mt-1 text-xl font-bold">Освоение дерева навыков</h2><div className="mt-5 flex items-end justify-between"><b className="text-4xl text-violet-200">{profile.learning_percent}%</b><span className="text-sm text-slate-400">Пройдено уровней: {profile.learning_completed || 0} из {profile.learning_total || 0}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-violet-400" style={{ width: `${profile.learning_percent}%` }} /></div><button onClick={() => nav("/training/tree")} className="subtle-button mt-5">Продолжить обучение</button></section></div>

    <section className="glass rounded-3xl p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="eyebrow">ДОСТИЖЕНИЯ</div><h2 className="mt-1 text-xl font-bold">{profile.achievement_details?.length || 0} получено</h2></div><button className="subtle-button" onClick={() => setAchievementTab(achievementTab === "all" ? "earned" : "all")}>{achievementTab === "all" ? "К полученным" : "Все достижения →"}</button></div>{achievementTab === "earned" ? <div className="achievement-overview">{(profile.achievement_details || []).slice(0, showAllEarned ? undefined : 6).map((item) => <div key={item.code}><span>★</span><b>{item.name}</b></div>)}{!profile.achievement_details?.length && <p className="text-sm text-slate-500">Первое достижение появится после завершения переговоров.</p>}{(profile.achievement_details?.length || 0) > 6 && <button onClick={() => setShowAllEarned((value) => !value)} className="achievement-more">{showAllEarned ? "Свернуть" : `Ещё ${profile.achievement_details.length - 6} полученных →`}</button>}</div> : <div className="mt-5 grid gap-3 md:grid-cols-2">{(profile.achievement_catalog || []).map((item) => <article key={item.code} className={`rounded-2xl border p-4 ${item.unlocked ? "border-cyan-300/30 bg-cyan-300/5" : "border-white/10 bg-white/[.02]"}`}><div className="flex items-start justify-between gap-3"><div><b>{item.unlocked ? "★ " : "◇ "}{item.name}</b><p className="mt-1 text-sm text-slate-400">{item.condition}</p></div><span className="text-sm text-cyan-100">{item.current}/{item.target}</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-gradient-to-r from-cyan-400 to-violet-400" style={{ width: `${Math.min(100, item.current / item.target * 100)}%` }} /></div></article>)}</div>}</section>

  </div>;
}

function Stat({ value, label }) { return <div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3"><b className="block text-lg text-cyan-100">{value}</b><span className="text-xs text-slate-400">{label}</span></div>; }
function Mini({ value, label }) { return <div className="rounded-2xl bg-white/5 p-3"><b className="block text-2xl">{value}</b><span className="text-xs text-slate-400">{label}</span></div>; }
function NegotiationProfile({ analysis }) { if(!analysis)return null; if(!analysis.ready)return <div className="mt-3 rounded-2xl border border-violet-300/20 bg-violet-300/5 p-4"><b className="text-violet-100">ИИ-анализ ещё собирает материал</b><p className="mt-1 text-sm text-slate-300">Для качественного анализа нужно завершить ещё {analysis.needed} ИИ-диалогов: сейчас {analysis.ai_dialogues} из 10.</p><p className="mt-3 text-xs text-slate-400">Уже будут учтены: сценарии — {analysis.scenario_sessions}, переговоры с друзьями — {analysis.friend_sessions}. {analysis.note}</p></div>; return <div className="mt-3 rounded-2xl border border-cyan-300/20 bg-cyan-300/5 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><b className="text-cyan-100">ИИ-анализ · {analysis.title}</b><p className="mt-1 text-sm text-slate-300">{analysis.summary}</p></div><span className="text-xs text-slate-400">Уверенность: {analysis.confidence}</span></div><p className="mt-3 text-sm text-emerald-100">Рекомендация: {analysis.recommendations?.[0]}</p><p className="mt-3 text-xs text-slate-400">Учтено: {analysis.ai_dialogues} ИИ-диалогов · {analysis.scenario_sessions} сценариев · {analysis.friend_sessions} переговоров с друзьями. {analysis.note}</p></div>; }
function Info({ text }) { return <details className="relative inline-block text-sm font-normal"><summary className="cursor-pointer list-none rounded-full border border-cyan-300/50 px-2 py-0.5 text-xs text-cyan-200">!</summary><span className="absolute left-0 top-8 z-30 w-64 rounded-xl border border-white/15 bg-slate-950 p-3 text-xs leading-5 text-slate-200 shadow-xl">{text}</span></details>; }
