import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../api.js";

const difficultyLabel = { easy: "Легко", medium: "Средне", hard: "Сложно", expert: "Эксперт", brutal: "Эксперт" };

export default function Scenarios() {
  const nav = useNavigate();
  const [scenarios, setScenarios] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("Все"); const [role, setRole] = useState("Все"); const [difficulty, setDifficulty] = useState("Все"); const [skill, setSkill] = useState("Все"); const [selected, setSelected] = useState(null);
  async function load() { setLoading(true); setError(""); try { setScenarios(await api("/api/scenarios")); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const categories = ["Все", ...new Set(scenarios.map((s) => s.category).filter(Boolean))]; const roles = ["Все", ...new Set(scenarios.map((s) => s.roles?.player).filter(Boolean))]; const skills = ["Все", ...new Set(scenarios.flatMap((s) => s.skills || []))];
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return scenarios.filter((s) => { const text = [s.title, s.description, s.context, s.roles?.player, s.opponent, ...(s.skills || [])].join(" ").toLowerCase(); return (!q || text.includes(q)) && (category === "Все" || s.category === category) && (role === "Все" || s.roles?.player === role) && (difficulty === "Все" || s.difficulty === difficulty) && (skill === "Все" || (s.skills || []).includes(skill)); }); }, [scenarios, query, category, role, difficulty, skill]);
  const reset = () => { setQuery(""); setCategory("Все"); setRole("Все"); setDifficulty("Все"); setSkill("Все"); };
  return <div><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="eyebrow">ОФЛАЙН-ТРЕНИРОВКИ</div><h1 className="text-3xl font-extrabold">Сценарные переговоры</h1><p className="mt-2 max-w-3xl text-slate-400">Тренируйтесь на готовых деловых ситуациях, принимайте решения и смотрите, как стратегия влияет на исход переговоров.</p></div><div className="glass rounded-2xl px-4 py-3 text-sm text-slate-300">{scenarios.length} сценариев · полностью офлайн</div></div>
    <section className="glass mt-6 rounded-3xl p-5"><div className="font-semibold">Начните первую тренировку</div><div className="mt-3 flex flex-wrap gap-2">{scenarios.filter((s) => ["hr_firing_01", "sales_discount_01", "salary_talk_01"].includes(s.id)).map((s) => <button key={s.id} onClick={() => setSelected(s)} className="rounded-xl border border-cyan-300/30 px-3 py-2 text-sm text-cyan-100 hover:bg-cyan-400/10">{s.title}</button>)}</div></section>
    <section className="glass mt-6 rounded-3xl p-5"><div className="grid gap-3 md:grid-cols-5"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Найти сценарий" className="rounded-xl bg-black/30 p-3 ring-1 ring-white/10 md:col-span-2" /><Filter value={category} onChange={setCategory} options={categories} label="Категория" /><Filter value={role} onChange={setRole} options={roles} label="Роль" /><Filter value={difficulty} onChange={setDifficulty} options={["Все", "easy", "medium", "hard", "expert"]} labels={difficultyLabel} label="Сложность" /><Filter value={skill} onChange={setSkill} options={skills} label="Навык" /></div></section>
    {loading && <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1, 2, 3, 4, 5, 6].map((n) => <div key={n} className="h-64 animate-pulse rounded-3xl bg-white/5" />)}</div>}{error && <div className="mt-6 glass rounded-3xl p-6 text-rose-200">Не удалось загрузить сценарии. <button onClick={load} className="ml-2 text-cyan-300 underline">Повторить</button></div>}{!loading && !error && !filtered.length && <div className="mt-6 glass rounded-3xl p-6 text-slate-300">Сценарии по выбранным фильтрам не найдены. <button onClick={reset} className="ml-2 text-cyan-300 underline">Сбросить фильтры</button></div>}
    <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((s) => <article key={s.id} className="glass flex min-h-64 flex-col rounded-3xl p-5"><div className="flex items-center justify-between gap-3 text-xs"><span className="text-cyan-300">{s.category}</span><span className="text-slate-400">≈ {s.minutes || 7} мин · {difficultyLabel[s.difficulty] || s.difficulty}</span></div><h2 className="mt-3 text-xl font-bold">{s.title}</h2><p className="mt-2 flex-1 text-sm text-slate-400">{s.description || s.context}</p><div className="mt-3 text-sm text-slate-300">Вы: {s.roles?.player} · Оппонент: {s.opponent || s.roles?.opponent}</div><div className="mt-3 flex flex-wrap gap-1">{(s.skills || []).slice(0, 4).map((item) => <span key={item} className="rounded-full bg-cyan-400/10 px-2 py-1 text-xs text-cyan-100">{item}</span>)}</div><button onClick={() => setSelected(s)} className="mt-4 rounded-2xl border border-cyan-300/30 px-4 py-2 text-sm font-semibold text-cyan-100 hover:bg-cyan-400/10">Подробнее</button></article>)}</div>
    {selected && <ScenarioModal scenario={selected} onClose={() => setSelected(null)} onStart={() => nav(`/setup?preset=${selected.id}`)} />}</div>;
}
function Filter({ value, onChange, options, label, labels = {} }) { return <label className="text-xs text-slate-400">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 w-full rounded-xl bg-black/30 p-3 text-sm text-white ring-1 ring-white/10">{options.map((item) => <option key={item} value={item}>{labels[item] || item}</option>)}</select></label>; }
function ScenarioModal({ scenario, onClose, onStart }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" onMouseDown={onClose}><section className="glass max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl p-6" onMouseDown={(e) => e.stopPropagation()}><div className="flex justify-between gap-4"><div><div className="text-sm text-cyan-300">{scenario.category}</div><h2 className="text-2xl font-bold">{scenario.title}</h2></div><button onClick={onClose} className="text-slate-400">×</button></div><Info label="Ситуация" value={scenario.context} /><Info label="Ваша роль" value={scenario.roles?.player} /><Info label="Оппонент" value={scenario.opponent || scenario.roles?.opponent} /><Info label="Ваша цель" value={scenario.goal} /><Info label="Что тренируем" value={(scenario.skills || []).join(" · ")} /><Info label="Сложность и длительность" value={`${difficultyLabel[scenario.difficulty] || scenario.difficulty} · ≈ ${scenario.minutes || 7} минут`} />{scenario.features?.length > 0 && <Info label="Особенности" value={scenario.features.join(" · ")} />}<button onClick={onStart} className="mt-5 w-full rounded-2xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950">Начать переговоры</button></section></div>; }
function Info({ label, value }) { return <div className="mt-4"><div className="text-xs uppercase tracking-wide text-slate-500">{label}</div><div className="mt-1 text-slate-200">{value}</div></div>; }
