import PageHeader from "../design/PageHeader.jsx";
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { api } from "../api.js";
import TrainingNavigation from "../components/training/TrainingNavigation.jsx";
import { answerQualityLabels, theoryAnswerQuality } from "../components/answerQuality.js";

export function TheoryCatalog() {
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  const nav = useNavigate();
  useEffect(() => { api("/api/theory").then(setData).catch((e) => setError(e.message)); }, []);
  if (error) return <div className="product-error" role="alert"><p>{error}</p><button className="subtle-button" onClick={() => { setError(""); api("/api/theory").then(setData).catch((failure) => setError(failure.message)); }}>Повторить загрузку</button></div>;
  if (!data) return <p className="product-loading" role="status">Загружаем уроки…</p>;
  const modules = data.modules || [{ ...data.module, lessons: data.lessons, completed: data.completed, total: data.total }];
  return <section className="theory-catalog"><TrainingNavigation fallback="/training" />
    <PageHeader eyebrow="Теория · Инструменты" title={data.module.title} description="Десять методов: от подготовки к точному исследованию и созданию сделки."><span className="ui-context-badge">{data.completed} из {data.total} уроков завершено</span></PageHeader>
    {data.course && <TheoryCourseResult course={data.course} onPractice={() => nav("/scenarios")} onRepeat={(lesson) => nav(`/theory/${lesson.id}`)} />}
    <div className="theory-modules">{modules.map((module) => <TheoryModuleSection key={module.id} module={module} onOpen={(lesson) => nav(`/theory/${lesson.id}`)} />)}</div>
  </section>;
}

function statusLabel(progress) { return progress.status === "not_started" ? "Не начат" : progress.status === "in_progress" ? "В процессе" : progress.status === "mastered" ? "Уверенно освоен" : "Изучен"; }
function TheoryModuleSection({ module, onOpen }) { return <section className="theory-module-section" aria-labelledby={`module-${module.id}`}><header><div><div className="eyebrow">БЛОК {String(module.order).padStart(2, "0")}</div><h2 id={`module-${module.id}`}>{module.title}</h2><p>{module.description}</p></div><span className="theory-module-progress">{module.completed} из {module.total}</span></header><div className="theory-catalog-list">{module.lessons.map((lesson) => <article key={lesson.id} className={`theory-lesson-card${lesson.unlocked ? "" : " is-locked"}`}><div className="theory-lesson-number">{String(lesson.order).padStart(2, "0")}</div><div className="theory-lesson-summary"><span>УРОК · ~{lesson.duration_minutes} МИН</span><h3>{lesson.title}</h3><p>{lesson.subtitle}</p><small>{lesson.unlocked ? statusLabel(lesson.progress) : `Откроется после урока ${lesson.order - 1}`}{lesson.progress.best_practice_score != null && ` · лучший результат ${lesson.progress.best_practice_score}%`}</small></div><button className="primary-button" disabled={!lesson.unlocked} aria-describedby={!lesson.unlocked ? `lock-${lesson.id}` : undefined} onClick={() => onOpen(lesson)}>{!lesson.unlocked ? "Закрыт" : lesson.progress.status === "not_started" ? "Начать" : lesson.progress.status === "in_progress" ? "Продолжить" : "Повторить"} →</button>{!lesson.unlocked && <span id={`lock-${lesson.id}`} className="sr-only">Сначала завершите предыдущий урок</span>}</article>)}</div></section>; }
function TheoryCourseResult({ course, onPractice, onRepeat }) { return <section className="theory-course-result glass"><div><div className="eyebrow">КУРС ЗАВЕРШЁН</div><h2>Базовый теоретический курс завершён</h2><p>Вы изучили 10 методов. Средний лучший результат: <b>{course.average_score}%</b>.</p></div><div className="theory-course-columns"><CourseList title="Уверенные методы" items={course.strongest} /><CourseList title="Стоит повторить" items={course.to_repeat} action={onRepeat} /></div><div className="mt-5 flex flex-wrap gap-3"><button className="primary-button" onClick={onPractice}>Перейти к сюжетной практике →</button></div></section>; }
function CourseList({ title, items, action }) { return <div><h3>{title}</h3><ul>{items.map((item) => <li key={item.id}>{action ? <button className="subtle-button" onClick={() => action(item)}>{item.title}</button> : <span>{item.title}</span>} <small>{item.score}%</small></li>)}</ul></div>; }

export function TheoryLesson() {
  const { lessonId } = useParams(); const nav = useNavigate();
  const [data, setData] = useState(null); const [step, setStep] = useState(0); const [selected, setSelected] = useState(null); const [answers, setAnswers] = useState({}); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = () => api(`/api/theory/${lessonId}`).then((lesson) => { setData(lesson); setStep(lesson.progress.current_step); setAnswers(lesson.answered || {}); });
  useEffect(() => { load().catch((e) => setError(e.message)); }, [lessonId]);
  async function move(next) { setBusy(true); setError(""); try { await api(`/api/theory/${lessonId}/step`, { method: "PUT", body: { current_step: next } }); setStep(next); setSelected(null); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function begin() { setBusy(true); setError(""); try { await api(`/api/theory/${lessonId}/start`, { method: "POST" }); setAnswers({}); setResult(null); await move(1); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function repeatPractice() { setBusy(true); setError(""); try { await api(`/api/theory/${lessonId}/start`, { method: "POST" }); setAnswers({}); setResult(null); await move(data.sections.length + 2); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function submit(exercise) { setBusy(true); setError(""); try { const reply = await api(`/api/theory/${lessonId}/practice/${exercise.id}`, { method: "POST", body: { option_id: selected } }); setAnswers((old) => ({ ...old, [exercise.id]: reply })); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function finish() { setBusy(true); setError(""); try { const completed = await api(`/api/theory/${lessonId}/complete`, { method: "POST" }); setResult(completed); setStep(completed.progress.current_step); setData((old) => ({ ...old, progress: completed.progress })); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  if (error && !data) return <div className="product-error" role="alert"><p>{error}</p><button className="subtle-button" onClick={() => nav("/theory")}>К каталогу</button></div>;
  if (!data) return <p className="product-loading" role="status">Загружаем урок…</p>;
  const mistakesStep = data.sections.length + 1;
  const practiceStart = mistakesStep + 1;
  const practiceEnd = practiceStart + data.practice.length - 1;
  const exercise = step >= practiceStart && step <= practiceEnd ? data.practice[step - practiceStart] : null;
  const exerciseAnswer = exercise ? answers[exercise.id] : null;
  const exerciseQuality = exerciseAnswer ? theoryAnswerQuality(exerciseAnswer.quality) : null;
  const isResult = step > practiceEnd || result;
  return <section className="theory-lesson"><TrainingNavigation fallback="/theory" /><header className="theory-lesson-head"><div className="eyebrow">УРОК {data.order} · ~{data.duration_minutes} МИН</div><h1 className="mt-2 text-3xl font-extrabold">{data.title}</h1><p className="mt-2 text-slate-400">{data.subtitle}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10" role="progressbar" aria-label="Прогресс урока" aria-valuenow={Math.min(100, Math.round(((step + 1) / (practiceEnd + 2)) * 100))} aria-valuemin={0} aria-valuemax={100}><i className="block h-full bg-lime-300" style={{ width: `${Math.min(100, ((step + 1) / (practiceEnd + 2)) * 100)}%` }} /></div></header>{error && <p className="mt-4 text-rose-300" role="alert">{error}</p>}
    {step === 0 && <Card title="Зачем это нужно"><p>{data.objectives.map((item) => `• ${item}`).join("\n")}</p><button disabled={busy} className="primary-button mt-6" onClick={begin}>Начать урок →</button></Card>}
    {step >= 1 && step <= data.sections.length && <Card title={data.sections[step - 1].title}><p>{data.sections[step - 1].body}</p>{data.sections[step - 1].callout && <aside className="mt-5 rounded-2xl border border-lime-300/25 bg-lime-300/10 p-4 text-lime-100">{data.sections[step - 1].callout}</aside>}{data.sections[step - 1].example && <aside className="mt-5 rounded-2xl bg-white/5 p-4 text-slate-300">{data.sections[step - 1].example}</aside>}<Controls step={step} move={move} busy={busy} /></Card>}
    {step === mistakesStep && <Card title="Типичные ошибки и шпаргалка"><h2 className="font-bold text-lime-100">Чего избегать</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-slate-300">{data.mistakes.map((item) => <li key={item}>{item}</li>)}</ul><h2 className="mt-6 font-bold text-lime-100">Перед разговором</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-slate-300">{data.cheat_sheet.map((item) => <li key={item}>{item}</li>)}</ul><Visualizations items={data.visualizations} /><Controls step={step} move={move} label="К практике" busy={busy} /></Card>}
    {exercise && <Card title={`Практика ${step - practiceStart + 1} из ${data.practice.length}`}><p className="rounded-2xl bg-white/5 p-4 text-slate-300">{exercise.context}</p><h2 className="mt-5 text-xl font-bold">{exercise.question}</h2>
      <div className="mt-5 grid gap-3">{exercise.options.map((option) => {
        const revealed = exerciseAnswer?.option_id === option.id;
        return <button key={option.id} disabled={Boolean(exerciseAnswer) || busy} aria-pressed={selected === option.id || revealed} onClick={() => setSelected(option.id)} className={`answer-button ${selected === option.id ? "selected" : ""}${revealed ? ` answer-quality-revealed answer-quality-${exerciseQuality}` : ""}`}><span>{option.text}</span>{revealed && <span className={`answer-quality-badge answer-quality-${exerciseQuality}`}>{answerQualityLabels[exerciseQuality]}</span>}</button>;
      })}</div>
      {exerciseAnswer && <div className={`choice-feedback answer-quality-revealed answer-quality-${exerciseQuality}`}><b>{answerQualityLabels[exerciseQuality]}</b><p>{exerciseAnswer.feedback}</p><small>{exerciseAnswer.explanation}</small></div>}
      <div className="mt-6 flex items-center justify-between gap-3"><button disabled={busy} className="subtle-button" onClick={() => move(step - 1)}>Назад</button>{exerciseAnswer ? <button className="primary-button" onClick={() => step === practiceEnd ? finish() : move(step + 1)} disabled={busy}>{busy ? "Сохраняем…" : step === practiceEnd ? "Завершить урок" : "Продолжить"} →</button> : <button disabled={!selected || busy} onClick={() => submit(exercise)} className="primary-button">Ответить</button>}</div>
    </Card>}
    {isResult && <Card title="Итог урока"><div className="text-5xl font-extrabold text-lime-200">{result?.score ?? data.progress.best_practice_score ?? 0}%</div><p className="mt-4 text-lg">{result?.status_label || "Урок завершён"}</p><p className="mt-3 text-slate-400">Запомните: {data.cheat_sheet.at(-1)}</p><div className="mt-6 flex flex-wrap gap-3"><button className="subtle-button" disabled={busy} onClick={repeatPractice}>Повторить практику</button><button className="primary-button" disabled={busy} onClick={() => nav("/theory")}>К теории</button>{result?.next_lesson_id && <button className="primary-button" disabled={busy} onClick={() => nav(`/theory/${result.next_lesson_id}`)}>Следующий урок →</button>}{result?.course_completed && <button className="primary-button" disabled={busy} onClick={() => nav("/scenarios")}>К сюжетной практике →</button>}</div><Sources items={data.sources} /></Card>}
    {!isResult && <Sources items={data.sources} />}
  </section>;
}

function Card({ title, children }) { return <article className="glass mt-6 rounded-3xl p-6 md:p-8"><h2 className="text-2xl font-bold">{title}</h2><div className="mt-4 whitespace-pre-line leading-7 text-slate-300">{children}</div></article>; }
function Controls({ step, move, label = "Далее", busy }) { return <div className="mt-7 flex justify-between"><button className="subtle-button" onClick={() => move(step - 1)} disabled={step <= 1 || busy}>Назад</button><button className="primary-button" onClick={() => move(step + 1)} disabled={busy}>{label} →</button></div>; }
function Sources({ items }) { if (!items?.length) return null; return <details className="mt-6"><summary className="cursor-pointer text-lime-200">Источники урока</summary><ul className="mt-3 space-y-3 text-sm">{items.map((item) => <li key={item.url}><a className="text-lime-200 underline" href={item.url} target="_blank" rel="noreferrer">{item.title}</a><span className="block text-slate-400">{item.organization}</span></li>)}</ul></details>; }
function Visualizations({ items }) { if (!items?.length) return null; return <div className="mt-7 grid gap-4">{items.map((item) => <section key={item.title} className="rounded-2xl border border-lime-300/20 bg-lime-300/5 p-4"><b className="text-lime-100">{item.title}</b>{item.type === "range" && <div className="mt-4"><div className="h-3 rounded-full bg-gradient-to-r from-lime-400 via-emerald-300 to-lime-400" /><div className="mt-2 flex justify-between gap-3 text-xs text-slate-300"><span>{item.left_label}</span><span>{item.right_label}</span></div></div>}{item.type === "gap" && <div className="mt-4"><div className="h-3 rounded-full bg-slate-600" /><div className="mt-2 flex justify-between gap-3 text-xs text-slate-300"><span>{item.left_label}</span><span>{item.right_label}</span></div></div>}{item.type === "comparison" && <div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{item.columns.map((column) => <th className="p-2 text-lime-100" key={column}>{column}</th>)}</tr></thead><tbody>{item.rows.map((row, index) => <tr className="border-t border-white/10" key={index}>{row.map((cell) => <td className="p-2" key={cell}>{cell}</td>)}</tr>)}</tbody></table></div>}{item.items && <div className="mt-3 flex flex-wrap gap-2">{item.items.map((value) => <span key={value} className="rounded-full bg-white/10 px-3 py-1 text-sm">{value}</span>)}</div>}<p className="mt-3 text-sm text-slate-400">{item.note}</p></section>)}</div>; }
