import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { api } from "../api.js";

export default function TrainingSession() {
  const { programId } = useParams(); const nav = useNavigate(); const [data,setData]=useState(null); const [index,setIndex]=useState(0); const [answer,setAnswer]=useState(""); const [result,setResult]=useState(null); const [busy,setBusy]=useState(false);
  useEffect(()=>{api(`/api/learning/programs/${programId}`).then(setData).catch((e)=>alert(e.message));},[programId]);
  if(!data) return <div className="text-slate-400">Загрузка упражнения…</div>; const ex=data.exercises[index]; if(!ex) return <div className="glass rounded-3xl p-6"><h1 className="text-2xl font-bold">Блок завершён</h1><button className="mt-4 text-cyan-300" onClick={()=>nav("/learn")}>К программам</button></div>;
  async function submit(optionId){setBusy(true);try{const r=await api(`/api/learning/programs/${programId}/exercises/${ex.id}`,{method:"POST",body:{option_id:optionId,answer:answer||null}});setResult(r);setData((d)=>({...d,...r.progress}));}catch(e){alert(e.message)}finally{setBusy(false)}}
  return <div className="mx-auto max-w-3xl"><div className="mb-4 text-sm text-cyan-300">{data.title} · {index+1}/{data.exercises.length}</div><div className="glass rounded-3xl p-6"><h1 className="text-2xl font-bold">{ex.title}</h1>{ex.dialogue?.map((line,i)=><p key={i} className="mt-3 rounded-xl bg-white/5 p-3">{line}</p>)}<p className="mt-5 text-slate-300">{ex.prompt}</p>{ex.goal&&<p className="mt-3 rounded-xl border border-violet-400/30 p-3 text-violet-100">Попробуйте: {ex.goal}</p>}{ex.options?.length ? <div className="mt-5 grid gap-3">{ex.options.map(o=><button key={o.id} disabled={busy||!!result} onClick={()=>submit(o.id)} className="rounded-2xl border border-white/15 p-4 text-left hover:border-cyan-300">{o.text}</button>)}</div> : <><textarea value={answer} onChange={e=>setAnswer(e.target.value)} disabled={!!result} rows="4" className="mt-5 w-full rounded-2xl bg-black/30 p-4" placeholder="Напишите свой ответ…"/><button disabled={busy||!!result} onClick={()=>submit(null)} className="mt-3 rounded-xl bg-cyan-400 px-4 py-3 font-semibold text-slate-950">Проверить ответ</button></>}{result&&<div className={`mt-5 rounded-2xl p-4 ${result.ok?"bg-emerald-500/15 text-emerald-100":"bg-amber-500/15 text-amber-100"}`}>{result.ok?"✓ ":"○ "}{result.feedback}<button className="ml-4 text-cyan-200" onClick={()=>{setResult(null);setAnswer("");setIndex(i=>i+1)}}>Продолжить</button></div>}</div></div>;
}
